In [1]:
import pandas as pd
import numpy as np
import time
from pykrx import stock
import FinanceDataReader as fdr
import warnings

warnings.filterwarnings(action='ignore')

In [31]:
import os
os.getcwd()

'C:\\Users\\PC\\OneDrive\\Data Science\\Weak-supervision\\생존편향 제거'

In [2]:
df_ = pd.read_csv(r'C:\Users\PC\OneDrive\Data Science\Weak-supervision\생존편향 제거\완료된 데이터\remove_survival_bias 데이터\new_df_bfconv.csv', encoding='euc-kr').set_index('Symbol Name')
df_

,Symbol,20100101,20100102,20100103,20100104,20100105,20100106,20100107,20100108,20100109,...,20191222,20191223,20191224,20191225,20191226,20191227,20191228,20191229,20191230,20191231
Symbol Name,,,,,,,,,,,,,,,,,,,,,
조흥은행,A000010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
조흥은행(1신),A000011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
조흥은행(2신),A000012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
동화약품,A000020,Y,Y,Y,Y,Y,Y,Y,Y,Y,...,N,N,N,N,N,N,N,N,N,N
동화약품공업(1신),A000021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
잉글우드랩,A950140,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,N,N,N,N,N,N,N,N,N,N
코오롱티슈진,A950160,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,N,N,N,N,N,N,N,N,N,N
JTC,A950170,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,N,N,N,N,N,N,N,N,N,N
SNK,A950180,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,N,N,N,N,N,N,N,N,N,N
편입개수,NaN,200.0,200.0,200.0,200.0,200.0,200.0,200.0,200.0,200.0,...,200.0,200.0,200.0,200.0,200.0,200.0,200.0,200.0,200.0,200.0

In [4]:
# convert symbol to eliminate useless 'A' (ex. A000010 -> 000010)
def symbol_convertor(str_):
    return str_[1:]

# 전체 기업코드 변환
symbol_origin = list(df_.loc[:'SNK','Symbol'].values)
symbol_origin = list(map(symbol_convertor, symbol_origin))

In [5]:
symbol_name_origin = list(df_.index.values)[:-1]   # 전체 기업이름(마지막 '편입개수'행만 빼고)

In [15]:
# make dictionary for corporate name & corporate code
symbol_dic = {}
for i in range(len(symbol_origin)):
    name = symbol_name_origin[i]
    code = symbol_origin[i]
    symbol_dic[name] = code
list(symbol_dic.items())[:5]

[('조흥은행', '000010'),
 ('조흥은행(1신)', '000011'),
 ('조흥은행(2신)', '000012'),
 ('동화약품', '000020'),
 ('동화약품공업(1신)', '000021')]

In [16]:
date_df = pd.read_csv(r'C:\Users\PC\OneDrive\Data Science\Weak-supervision\생존편향 제거\완료된 데이터\date_df.csv', encoding='euc-kr').set_index('Date')
date_df

,AK홀딩스,BGF,BGF리테일,BNK금융지주,CJ,CJ CGV,CJ대한통운,CJ제일제당,DB손해보험,DB하이텍,...,현대해상,현대홈쇼핑,호텔신라,화신,효성,효성중공업,후성,휠라홀딩스,휴비스,휴켐스
Date,,,,,,,,,,,,,,,,,,,,,
20100101,O,X,X,X,O,X,O,O,X,O,...,X,X,X,X,O,X,O,X,X,O
20100102,O,X,X,X,O,X,O,O,X,O,...,X,X,X,X,O,X,O,X,X,O
20100103,O,X,X,X,O,X,O,O,X,O,...,X,X,X,X,O,X,O,X,X,O
20100104,O,X,X,X,O,X,O,O,X,O,...,X,X,X,X,O,X,O,X,X,O
20100105,O,X,X,X,O,X,O,O,X,O,...,X,X,X,X,O,X,O,X,X,O
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20191227,O,O,O,O,O,O,O,O,O,O,...,O,O,O,X,O,O,O,O,X,O
20191228,O,O,O,O,O,O,O,O,O,O,...,O,O,O,X,O,O,O,O,X,O
20191229,O,O,O,O,O,O,O,O,O,O,...,O,O,O,X,O,O,O,O,X,O
20191230,O,O,O,O,O,O,O,O,O,O,...,O,O,O,X,O,O,O,O,X,O
20191231,O,O,O,O,O,O,O,O,O,O,...,O,O,O,X,O,O,O,O,X,O

In [17]:
# rename한 columns : KOSPI200 기업이름
lv2_companies_rename = list(date_df.columns.values)
lv2_companies_rename

['AK홀딩스',
 'BGF',
 'BGF리테일',
 'BNK금융지주',
 'CJ',
 'CJ CGV',
 'CJ대한통운',
 'CJ제일제당',
 'DB손해보험',
 'DB하이텍',
 'DGB금융지주',
 'GKL',
 'GS',
 'GS건설',
 'GS리테일',
 'HDC',
 'HDC현대산업개발',
 'HSD엔진',
 'JW중외제약',
 'JW홀딩스',
 'KB금융',
 '케이씨씨',
 'KC그린홀딩스',
 'KISCO홀딩스',
 'KPX케미칼',
 '케이티',
 '케이티앤지',
 'LF',
 'LG',
 'LG디스플레이',
 'LG상사',
 'LG생명과학',
 'LG생활건강',
 'LG유플러스',
 'LG이노텍',
 'LG전자',
 'LG하우시스',
 'LG화학',
 'LIG넥스원',
 'LS',
 'LS산전',
 'NAVER',
 'NH투자증권',
 'OCI',
 '포스코',
 'S&TC',
 'S&T모티브',
 'S&T중공업',
 'S-Oil',
 'SBS',
 'SK',
 'SKC',
 'SK네트웍스',
 'SK디스커버리',
 'SK이노베이션',
 'SK케미칼',
 'SK텔레콤',
 'SK하이닉스',
 'SPC삼립',
 'STX',
 'STX엔진',
 'STX조선해양',
 'STX중공업',
 '티비에이치글로벌',
 '강원랜드',
 '경방',
 '고려아연',
 '고려제강',
 '광동제약',
 '광전자',
 '국도화학',
 '금호산업',
 '금호석유화학',
 '금호전기',
 '금호타이어',
 '기아자동차',
 '기업은행',
 '남양유업',
 '남해화학',
 '넥센타이어',
 '넷마블',
 '녹십자',
 '녹십자홀딩스',
 '농심',
 '대교',
 '대구은행',
 '대덕GDS',
 '대덕전자',
 '대림산업',
 '대상',
 '대우건설',
 '대우조선해양',
 '대웅제약',
 '대원강업',
 '대한유화',
 '대한전선',
 '대한제강',
 '대한제당',
 '대한제분',
 '대한항공',
 '도레이케미칼',
 '동국제강',
 '동부제철',
 '동서',
 '동아쏘시오홀딩스',
 '동아에스티',
 '동양',
 '동원F&B',
 '동원시스템즈',
 '동일산업',
 '동화약품',
 '두산',
 '두산밥캣',
 '두산인프라코어',
 '두산중공업',
 '디와이',
 '디티알오토모티브',
 '락앤락',
 '롯데쇼핑',
 '롯데정밀화학',
 '롯데지주',
 '롯데칠성음료',
 '롯데케미칼',
 '롯데푸드',
 '롯데하이마트',
 '만도',
 '메리츠종금증권',
 '모토닉',
 '무림P&P',
 '무림페이퍼',
 '무학',
 '미래에셋대우',
 '미래에셋증권',
 '벽산',
 '보령제약',
 '부광약품',
 '부산은행',
 '빙그레',
 '사조동아원',
 '삼광글라스',
 '삼성SDI',
 '삼성물산',
 '삼성바이오로직스',
 '삼성생명',
 '삼성에스디에스',
 '삼성엔지니어링',
 '삼성전기',
 '삼성전자',
 '삼성중공업',
 '삼성증권',
 '삼성카드',
 '삼성화재해상보험',
 '삼양사',
 '삼양제넥스',
 '삼양홀딩스',
 '삼영전자공업',
 '삼진제약',
 '서연',
 '서흥',
 '세방전지',
 '세아베스틸',
 '세아제강지주',
 '세원셀론텍',
 '세종공업',
 '세하',
 '셀트리온',
 '송원산업',
 '신도리코',
 '신성이엔지',
 '신세계',
 '신세계인터내셔날',
 '신한지주',
 '쌍용양회공업',
 '쌍용자동차',
 '아모레퍼시픽그룹',
 '아모레퍼시픽',
 '아세아',
 '아이에스동서',
 '알루코',
 '알바이오',
 '애경산업',
 '에스엘',
 '에스원',
 '에이블씨엔씨',
 '엔씨소프트',
 '엔케이',
 '영원무역',
 '영진약품',
 '영풍',
 '오뚜기',
 '오리온',
 '오리온홀딩스',
 '하나은행',
 '우리금융지주',
 '우리은행',
 '웅진에너지',
 '유니드',
 '유니온스틸',
 '유수홀딩스',
 '유한양행',
 '율촌화학',
 '이노션',
 '이마트',
 '이수화학',
 '인디에프',
 '일동홀딩스',
 '일성신약',
 '일신방직',
 '일양약품',
 '일진디스플',
 '일진머티리얼즈',
 '일진전기',
 '자화전자',
 '한국전기초자',
 '제일기획',
 '제일모직',
 '제일파마홀딩스',
 '조광피혁',
 '조선내화',
 '종근당',
 '종근당홀딩스',
 '카카오',
 '카프로',
 '아진카인텍',
 '케이피케미칼',
 '코리아써키트',
 '코스맥스',
 '코스맥스비티아이',
 '코오롱',
 '코오롱인더',
 '코웨이',
 '쿠쿠홀딩스',
 '큐로',
 '크라운해태홀딩스',
 '태광산업',
 '파미셀',
 '팜스코',
 '팬오션',
 '퍼시스',
 '포스코인터내셔널',
 '포스코플랜텍',
 '풍산',
 '하나금융지주',
 '하이트맥주',
 '하이트진로',
 '하이트진로홀딩스',
 '한국가스공사',
 '한국금융지주',
 '한국기술산업',
 '한국단자공업',
 '한국쉘석유',
 '한국전력공사',
 '한국제지',
 '한국조선해양',
 '한국철강',
 '한국카본',
 '한국콜마',
 '한국타이어앤테크놀로지',
 '한국테크놀로지그룹',
 '한국항공우주',
 '한독',
 '한라홀딩스',
 '한미반도체',
 '한미사이언스',
 '한미약품',
 '한샘',
 '한섬',
 '한세실업',
 '한솔케미칼',
 '한솔테크닉스',
 '한솔홀딩스',
 '한온시스템',
 '한올바이오파마',
 '한일현대시멘트',
 '한일홀딩스',
 '한전KPS',
 '한전기술',
 '한진중공업',
 '한진중공업홀딩스',
 '한화',
 '한화생명',
 '한화솔루션',
 '한화에어로스페이스',
 '한화화인케미칼',
 '현대건설',
 '현대그린푸드',
 '현대글로비스',
 '현대로템',
 '현대리바트',
 '현대모비스',
 '현대미포조선',
 '현대백화점',
 '현대상선',
 '현대엘리베이터',
 '현대위아',
 '현대제철',
 '현대중공업지주',
 '케이비증권',
 '현대자동차',
 '현대하이스코',
 '현대해상',
 '현대홈쇼핑',
 '호텔신라',
 '화신',
 '효성',
 '효성중공업',
 '후성',
 '휠라홀딩스',
 '휴비스',
 '휴켐스']

In [18]:
len(lv2_companies_rename)

310

In [19]:
daily_k200 = pd.read_csv(r'C:\Users\PC\OneDrive\Data Science\Weak-supervision\생존편향 제거\완료된 데이터\daily_k200.csv', encoding='euc-kr').set_index('Unnamed: 0')
daily_k200

,20100101,20100102,20100103,20100104,20100105,20100106,20100107,20100108,20100109,20100110,...,20191222,20191223,20191224,20191225,20191226,20191227,20191228,20191229,20191230,20191231
Unnamed: 0,,,,,,,,,,,,,,,,,,,,,
0,동화약품,동화약품,동화약품,동화약품,동화약품,동화약품,동화약품,동화약품,동화약품,동화약품,...,삼양홀딩스,삼양홀딩스,삼양홀딩스,삼양홀딩스,삼양홀딩스,삼양홀딩스,삼양홀딩스,삼양홀딩스,삼양홀딩스,삼양홀딩스
1,경방,경방,경방,경방,경방,경방,경방,경방,경방,경방,...,하이트진로,하이트진로,하이트진로,하이트진로,하이트진로,하이트진로,하이트진로,하이트진로,하이트진로,하이트진로
2,삼양홀딩스,삼양홀딩스,삼양홀딩스,삼양홀딩스,삼양홀딩스,삼양홀딩스,삼양홀딩스,삼양홀딩스,삼양홀딩스,삼양홀딩스,...,유한양행,유한양행,유한양행,유한양행,유한양행,유한양행,유한양행,유한양행,유한양행,유한양행
3,유한양행,유한양행,유한양행,유한양행,유한양행,유한양행,유한양행,유한양행,유한양행,유한양행,...,CJ대한통운,CJ대한통운,CJ대한통운,CJ대한통운,CJ대한통운,CJ대한통운,CJ대한통운,CJ대한통운,CJ대한통운,CJ대한통운
4,CJ대한통운,CJ대한통운,CJ대한통운,CJ대한통운,CJ대한통운,CJ대한통운,CJ대한통운,CJ대한통운,CJ대한통운,CJ대한통운,...,두산,두산,두산,두산,두산,두산,두산,두산,두산,두산
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,한진중공업,한진중공업,한진중공업,한진중공업,한진중공업,한진중공업,한진중공업,한진중공업,한진중공업,한진중공업,...,HDC현대산업개발,HDC현대산업개발,HDC현대산업개발,HDC현대산업개발,HDC현대산업개발,HDC현대산업개발,HDC현대산업개발,HDC현대산업개발,HDC현대산업개발,HDC현대산업개발
198,CJ제일제당,CJ제일제당,CJ제일제당,CJ제일제당,CJ제일제당,CJ제일제당,CJ제일제당,CJ제일제당,CJ제일제당,CJ제일제당,...,효성중공업,효성중공업,효성중공업,효성중공업,효성중공업,효성중공업,효성중공업,효성중공업,효성중공업,효성중공업
199,KB금융,KB금융,KB금융,KB금융,KB금융,KB금융,KB금융,KB금융,KB금융,KB금융,...,우리금융지주,우리금융지주,우리금융지주,우리금융지주,우리금융지주,우리금융지주,우리금융지주,우리금융지주,우리금융지주,우리금융지주
200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
daily_k200.fillna('')

,20100101,20100102,20100103,20100104,20100105,20100106,20100107,20100108,20100109,20100110,...,20191222,20191223,20191224,20191225,20191226,20191227,20191228,20191229,20191230,20191231
Unnamed: 0,,,,,,,,,,,,,,,,,,,,,
0,동화약품,동화약품,동화약품,동화약품,동화약품,동화약품,동화약품,동화약품,동화약품,동화약품,...,삼양홀딩스,삼양홀딩스,삼양홀딩스,삼양홀딩스,삼양홀딩스,삼양홀딩스,삼양홀딩스,삼양홀딩스,삼양홀딩스,삼양홀딩스
1,경방,경방,경방,경방,경방,경방,경방,경방,경방,경방,...,하이트진로,하이트진로,하이트진로,하이트진로,하이트진로,하이트진로,하이트진로,하이트진로,하이트진로,하이트진로
2,삼양홀딩스,삼양홀딩스,삼양홀딩스,삼양홀딩스,삼양홀딩스,삼양홀딩스,삼양홀딩스,삼양홀딩스,삼양홀딩스,삼양홀딩스,...,유한양행,유한양행,유한양행,유한양행,유한양행,유한양행,유한양행,유한양행,유한양행,유한양행
3,유한양행,유한양행,유한양행,유한양행,유한양행,유한양행,유한양행,유한양행,유한양행,유한양행,...,CJ대한통운,CJ대한통운,CJ대한통운,CJ대한통운,CJ대한통운,CJ대한통운,CJ대한통운,CJ대한통운,CJ대한통운,CJ대한통운
4,CJ대한통운,CJ대한통운,CJ대한통운,CJ대한통운,CJ대한통운,CJ대한통운,CJ대한통운,CJ대한통운,CJ대한통운,CJ대한통운,...,두산,두산,두산,두산,두산,두산,두산,두산,두산,두산
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,한진중공업,한진중공업,한진중공업,한진중공업,한진중공업,한진중공업,한진중공업,한진중공업,한진중공업,한진중공업,...,HDC현대산업개발,HDC현대산업개발,HDC현대산업개발,HDC현대산업개발,HDC현대산업개발,HDC현대산업개발,HDC현대산업개발,HDC현대산업개발,HDC현대산업개발,HDC현대산업개발
198,CJ제일제당,CJ제일제당,CJ제일제당,CJ제일제당,CJ제일제당,CJ제일제당,CJ제일제당,CJ제일제당,CJ제일제당,CJ제일제당,...,효성중공업,효성중공업,효성중공업,효성중공업,효성중공업,효성중공업,효성중공업,효성중공업,효성중공업,효성중공업
199,KB금융,KB금융,KB금융,KB금융,KB금융,KB금융,KB금융,KB금융,KB금융,KB금융,...,우리금융지주,우리금융지주,우리금융지주,우리금융지주,우리금융지주,우리금융지주,우리금융지주,우리금융지주,우리금융지주,우리금융지주
200,,,,,,,,,,,...,,,,,,,,,,
201,,,,,,,,,,,...,,,,,,,,,,

In [21]:
# lv2_index : 20100101 ~ 20191231 전체 기간이 담겨있는 Date list
lv2_index = list(date_df.index.values)
lv2_index = list(map(str, lv2_index))
lv2_index

['20100101',
 '20100102',
 '20100103',
 '20100104',
 '20100105',
 '20100106',
 '20100107',
 '20100108',
 '20100109',
 '20100110',
 '20100111',
 '20100112',
 '20100113',
 '20100114',
 '20100115',
 '20100116',
 '20100117',
 '20100118',
 '20100119',
 '20100120',
 '20100121',
 '20100122',
 '20100123',
 '20100124',
 '20100125',
 '20100126',
 '20100127',
 '20100128',
 '20100129',
 '20100130',
 '20100131',
 '20100201',
 '20100202',
 '20100203',
 '20100204',
 '20100205',
 '20100206',
 '20100207',
 '20100208',
 '20100209',
 '20100210',
 '20100211',
 '20100212',
 '20100213',
 '20100214',
 '20100215',
 '20100216',
 '20100217',
 '20100218',
 '20100219',
 '20100220',
 '20100221',
 '20100222',
 '20100223',
 '20100224',
 '20100225',
 '20100226',
 '20100227',
 '20100228',
 '20100301',
 '20100302',
 '20100303',
 '20100304',
 '20100305',
 '20100306',
 '20100307',
 '20100308',
 '20100309',
 '20100310',
 '20100311',
 '20100312',
 '20100313',
 '20100314',
 '20100315',
 '20100316',
 '20100317',
 '20100318',
 '20100319',
 '20100320',
 '20100321',
 '20100322',
 '20100323',
 '20100324',
 '20100325',
 '20100326',
 '20100327',
 '20100328',
 '20100329',
 '20100330',
 '20100331',
 '20100401',
 '20100402',
 '20100403',
 '20100404',
 '20100405',
 '20100406',
 '20100407',
 '20100408',
 '20100409',
 '20100410',
 '20100411',
 '20100412',
 '20100413',
 '20100414',
 '20100415',
 '20100416',
 '20100417',
 '20100418',
 '20100419',
 '20100420',
 '20100421',
 '20100422',
 '20100423',
 '20100424',
 '20100425',
 '20100426',
 '20100427',
 '20100428',
 '20100429',
 '20100430',
 '20100501',
 '20100502',
 '20100503',
 '20100504',
 '20100505',
 '20100506',
 '20100507',
 '20100508',
 '20100509',
 '20100510',
 '20100511',
 '20100512',
 '20100513',
 '20100514',
 '20100515',
 '20100516',
 '20100517',
 '20100518',
 '20100519',
 '20100520',
 '20100521',
 '20100522',
 '20100523',
 '20100524',
 '20100525',
 '20100526',
 '20100527',
 '20100528',
 '20100529',
 '20100530',
 '20100531',
 '20100601',
 '20100602',
 '20100603',
 '20100604',
 '20100605',
 '20100606',
 '20100607',
 '20100608',
 '20100609',
 '20100610',
 '20100611',
 '20100612',
 '20100613',
 '20100614',
 '20100615',
 '20100616',
 '20100617',
 '20100618',
 '20100619',
 '20100620',
 '20100621',
 '20100622',
 '20100623',
 '20100624',
 '20100625',
 '20100626',
 '20100627',
 '20100628',
 '20100629',
 '20100630',
 '20100701',
 '20100702',
 '20100703',
 '20100704',
 '20100705',
 '20100706',
 '20100707',
 '20100708',
 '20100709',
 '20100710',
 '20100711',
 '20100712',
 '20100713',
 '20100714',
 '20100715',
 '20100716',
 '20100717',
 '20100718',
 '20100719',
 '20100720',
 '20100721',
 '20100722',
 '20100723',
 '20100724',
 '20100725',
 '20100726',
 '20100727',
 '20100728',
 '20100729',
 '20100730',
 '20100731',
 '20100801',
 '20100802',
 '20100803',
 '20100804',
 '20100805',
 '20100806',
 '20100807',
 '20100808',
 '20100809',
 '20100810',
 '20100811',
 '20100812',
 '20100813',
 '20100814',
 '20100815',
 '20100816',
 '20100817',
 '20100818',
 '20100819',
 '20100820',
 '20100821',
 '20100822',
 '20100823',
 '20100824',
 '20100825',
 '20100826',
 '20100827',
 '20100828',
 '20100829',
 '20100830',
 '20100831',
 '20100901',
 '20100902',
 '20100903',
 '20100904',
 '20100905',
 '20100906',
 '20100907',
 '20100908',
 '20100909',
 '20100910',
 '20100911',
 '20100912',
 '20100913',
 '20100914',
 '20100915',
 '20100916',
 '20100917',
 '20100918',
 '20100919',
 '20100920',
 '20100921',
 '20100922',
 '20100923',
 '20100924',
 '20100925',
 '20100926',
 '20100927',
 '20100928',
 '20100929',
 '20100930',
 '20101001',
 '20101002',
 '20101003',
 '20101004',
 '20101005',
 '20101006',
 '20101007',
 '20101008',
 '20101009',
 '20101010',
 '20101011',
 '20101012',
 '20101013',
 '20101014',
 '20101015',
 '20101016',
 '20101017',
 '20101018',
 '20101019',
 '20101020',
 '20101021',
 '20101022',
 '20101023',
 '20101024',
 '20101025',
 '20101026',
 '20101027',
 '20101028',
 '20101029',
 '20101030',
 '20101031',
 '20101101',
 '20101102',
 '20101103',
 '20101104',
 '20101105',
 '20101106',
 '20101107',
 '20101108',
 '20101109',
 '20101110',
 '20101111',
 '20101112',
 '20101113',
 '20101114',
 '20101115',
 '20101116',
 '20101117',
 '20101118',
 '20101119',
 '20101120',
 '20101121',
 '20101122',
 '20101123',
 '20101124',
 '20101125',
 '20101126',
 '20101127',
 '20101128',
 '20101129',
 '20101130',
 '20101201',
 '20101202',
 '20101203',
 '20101204',
 '20101205',
 '20101206',
 '20101207',
 '20101208',
 '20101209',
 '20101210',
 '20101211',
 '20101212',
 '20101213',
 '20101214',
 '20101215',
 '20101216',
 '20101217',
 '20101218',
 '20101219',
 '20101220',
 '20101221',
 '20101222',
 '20101223',
 '20101224',
 '20101225',
 '20101226',
 '20101227',
 '20101228',
 '20101229',
 '20101230',
 '20101231',
 '20110101',
 '20110102',
 '20110103',
 '20110104',
 '20110105',
 '20110106',
 '20110107',
 '20110108',
 '20110109',
 '20110110',
 '20110111',
 '20110112',
 '20110113',
 '20110114',
 '20110115',
 '20110116',
 '20110117',
 '20110118',
 '20110119',
 '20110120',
 '20110121',
 '20110122',
 '20110123',
 '20110124',
 '20110125',
 '20110126',
 '20110127',
 '20110128',
 '20110129',
 '20110130',
 '20110131',
 '20110201',
 '20110202',
 '20110203',
 '20110204',
 '20110205',
 '20110206',
 '20110207',
 '20110208',
 '20110209',
 '20110210',
 '20110211',
 '20110212',
 '20110213',
 '20110214',
 '20110215',
 '20110216',
 '20110217',
 '20110218',
 '20110219',
 '20110220',
 '20110221',
 '20110222',
 '20110223',
 '20110224',
 '20110225',
 '20110226',
 '20110227',
 '20110228',
 '20110301',
 '20110302',
 '20110303',
 '20110304',
 '20110305',
 '20110306',
 '20110307',
 '20110308',
 '20110309',
 '20110310',
 '20110311',
 '20110312',
 '20110313',
 '20110314',
 '20110315',
 '20110316',
 '20110317',
 '20110318',
 '20110319',
 '20110320',
 '20110321',
 '20110322',
 '20110323',
 '20110324',
 '20110325',
 '20110326',
 '20110327',
 '20110328',
 '20110329',
 '20110330',
 '20110331',
 '20110401',
 '20110402',
 '20110403',
 '20110404',
 '20110405',
 '20110406',
 '20110407',
 '20110408',
 '20110409',
 '20110410',
 '20110411',
 '20110412',
 '20110413',
 '20110414',
 '20110415',
 '20110416',
 '20110417',
 '20110418',
 '20110419',
 '20110420',
 '20110421',
 '20110422',
 '20110423',
 '20110424',
 '20110425',
 '20110426',
 '20110427',
 '20110428',
 '20110429',
 '20110430',
 '20110501',
 '20110502',
 '20110503',
 '20110504',
 '20110505',
 '20110506',
 '20110507',
 '20110508',
 '20110509',
 '20110510',
 '20110511',
 '20110512',
 '20110513',
 '20110514',
 '20110515',
 '20110516',
 '20110517',
 '20110518',
 '20110519',
 '20110520',
 '20110521',
 '20110522',
 '20110523',
 '20110524',
 '20110525',
 '20110526',
 '20110527',
 '20110528',
 '20110529',
 '20110530',
 '20110531',
 '20110601',
 '20110602',
 '20110603',
 '20110604',
 '20110605',
 '20110606',
 '20110607',
 '20110608',
 '20110609',
 '20110610',
 '20110611',
 '20110612',
 '20110613',
 '20110614',
 '20110615',
 '20110616',
 '20110617',
 '20110618',
 '20110619',
 '20110620',
 '20110621',
 '20110622',
 '20110623',
 '20110624',
 '20110625',
 '20110626',
 '20110627',
 '20110628',
 '20110629',
 '20110630',
 '20110701',
 '20110702',
 '20110703',
 '20110704',
 '20110705',
 '20110706',
 '20110707',
 '20110708',
 '20110709',
 '20110710',
 '20110711',
 '20110712',
 '20110713',
 '20110714',
 '20110715',
 '20110716',
 '20110717',
 '20110718',
 '20110719',
 '20110720',
 '20110721',
 '20110722',
 '20110723',
 '20110724',
 '20110725',
 '20110726',
 '20110727',
 '20110728',
 '20110729',
 '20110730',
 '20110731',
 '20110801',
 '20110802',
 '20110803',
 '20110804',
 '20110805',
 '20110806',
 '20110807',
 '20110808',
 '20110809',
 '20110810',
 '20110811',
 '20110812',
 '20110813',
 '20110814',
 '20110815',
 '20110816',
 '20110817',
 '20110818',
 '20110819',
 '20110820',
 '20110821',
 '20110822',
 '20110823',
 '20110824',
 '20110825',
 '20110826',
 '20110827',
 '20110828',
 '20110829',
 '20110830',
 '20110831',
 '20110901',
 '20110902',
 '20110903',
 '20110904',
 '20110905',
 '20110906',
 '20110907',
 '20110908',
 '20110909',
 '20110910',
 '20110911',
 '20110912',
 '20110913',
 '20110914',
 '20110915',
 '20110916',
 '20110917',
 '20110918',
 '20110919',
 '20110920',
 '20110921',
 '20110922',
 '20110923',
 '20110924',
 '20110925',
 '20110926',
 '20110927',
 '20110928',
 '20110929',
 '20110930',
 '20111001',
 '20111002',
 '20111003',
 '20111004',
 '20111005',
 '20111006',
 '20111007',
 '20111008',
 '20111009',
 '20111010',
 '20111011',
 '20111012',
 '20111013',
 '20111014',
 '20111015',
 '20111016',
 '20111017',
 '20111018',
 '20111019',
 '20111020',
 '20111021',
 '20111022',
 '20111023',
 '20111024',
 '20111025',
 '20111026',
 '20111027',
 '20111028',
 '20111029',
 '20111030',
 '20111031',
 '20111101',
 '20111102',
 '20111103',
 '20111104',
 '20111105',
 '20111106',
 '20111107',
 '20111108',
 '20111109',
 '20111110',
 '20111111',
 '20111112',
 '20111113',
 '20111114',
 '20111115',
 '20111116',
 '20111117',
 '20111118',
 '20111119',
 '20111120',
 '20111121',
 '20111122',
 '20111123',
 '20111124',
 '20111125',
 '20111126',
 '20111127',
 '20111128',
 '20111129',
 '20111130',
 '20111201',
 '20111202',
 '20111203',
 '20111204',
 '20111205',
 '20111206',
 '20111207',
 '20111208',
 '20111209',
 '20111210',
 '20111211',
 '20111212',
 '20111213',
 '20111214',
 '20111215',
 '20111216',
 '20111217',
 '20111218',
 '20111219',
 '20111220',
 '20111221',
 '20111222',
 '20111223',
 '20111224',
 '20111225',
 '20111226',
 '20111227',
 '20111228',
 '20111229',
 '20111230',
 '20111231',
 '20120101',
 '20120102',
 '20120103',
 '20120104',
 '20120105',
 '20120106',
 '20120107',
 '20120108',
 '20120109',
 '20120110',
 '20120111',
 '20120112',
 '20120113',
 '20120114',
 '20120115',
 '20120116',
 '20120117',
 '20120118',
 '20120119',
 '20120120',
 '20120121',
 '20120122',
 '20120123',
 '20120124',
 '20120125',
 '20120126',
 '20120127',
 '20120128',
 '20120129',
 '20120130',
 '20120131',
 '20120201',
 '20120202',
 '20120203',
 '20120204',
 '20120205',
 '20120206',
 '20120207',
 '20120208',
 '20120209',
 '20120210',
 '20120211',
 '20120212',
 '20120213',
 '20120214',
 '20120215',
 '20120216',
 '20120217',
 '20120218',
 '20120219',
 '20120220',
 '20120221',
 '20120222',
 '20120223',
 '20120224',
 '20120225',
 '20120226',
 '20120227',
 '20120228',
 '20120229',
 '20120301',
 '20120302',
 '20120303',
 '20120304',
 '20120305',
 '20120306',
 '20120307',
 '20120308',
 '20120309',
 '20120310',
 '20120311',
 '20120312',
 '20120313',
 '20120314',
 '20120315',
 '20120316',
 '20120317',
 '20120318',
 '20120319',
 '20120320',
 '20120321',
 '20120322',
 '20120323',
 '20120324',
 '20120325',
 '20120326',
 '20120327',
 '20120328',
 '20120329',
 '20120330',
 '20120331',
 '20120401',
 '20120402',
 '20120403',
 '20120404',
 '20120405',
 '20120406',
 '20120407',
 '20120408',
 '20120409',
 '20120410',
 '20120411',
 '20120412',
 '20120413',
 '20120414',
 '20120415',
 '20120416',
 '20120417',
 '20120418',
 '20120419',
 '20120420',
 '20120421',
 '20120422',
 '20120423',
 '20120424',
 '20120425',
 '20120426',
 '20120427',
 '20120428',
 '20120429',
 '20120430',
 '20120501',
 '20120502',
 '20120503',
 '20120504',
 '20120505',
 '20120506',
 '20120507',
 '20120508',
 '20120509',
 '20120510',
 '20120511',
 '20120512',
 '20120513',
 '20120514',
 '20120515',
 '20120516',
 '20120517',
 '20120518',
 '20120519',
 '20120520',
 '20120521',
 '20120522',
 '20120523',
 '20120524',
 '20120525',
 '20120526',
 '20120527',
 '20120528',
 '20120529',
 '20120530',
 '20120531',
 '20120601',
 '20120602',
 '20120603',
 '20120604',
 '20120605',
 '20120606',
 '20120607',
 '20120608',
 '20120609',
 '20120610',
 '20120611',
 '20120612',
 '20120613',
 '20120614',
 '20120615',
 '20120616',
 '20120617',
 '20120618',
 '20120619',
 '20120620',
 '20120621',
 '20120622',
 '20120623',
 '20120624',
 '20120625',
 '20120626',
 '20120627',
 '20120628',
 '20120629',
 '20120630',
 '20120701',
 '20120702',
 '20120703',
 '20120704',
 '20120705',
 '20120706',
 '20120707',
 '20120708',
 '20120709',
 '20120710',
 '20120711',
 '20120712',
 '20120713',
 '20120714',
 '20120715',
 '20120716',
 '20120717',
 '20120718',
 '20120719',
 '20120720',
 '20120721',
 '20120722',
 '20120723',
 '20120724',
 '20120725',
 '20120726',
 '20120727',
 '20120728',
 '20120729',
 '20120730',
 '20120731',
 '20120801',
 '20120802',
 '20120803',
 '20120804',
 '20120805',
 '20120806',
 '20120807',
 '20120808',
 '20120809',
 '20120810',
 '20120811',
 '20120812',
 '20120813',
 '20120814',
 '20120815',
 '20120816',
 '20120817',
 '20120818',
 '20120819',
 '20120820',
 '20120821',
 '20120822',
 '20120823',
 '20120824',
 '20120825',
 '20120826',
 '20120827',
 '20120828',
 '20120829',
 '20120830',
 '20120831',
 '20120901',
 '20120902',
 '20120903',
 '20120904',
 '20120905',
 '20120906',
 '20120907',
 '20120908',
 '20120909',
 '20120910',
 '20120911',
 '20120912',
 '20120913',
 '20120914',
 '20120915',
 '20120916',
 '20120917',
 '20120918',
 '20120919',
 '20120920',
 '20120921',
 '20120922',
 '20120923',
 '20120924',
 '20120925',
 '20120926',
 ...]

In [22]:
# all_list에 20100101 ~ 20191231 기간동안의 모든 KOSPI200 리스트를 담음 (202 * 3,652 = 737,704)
all_list = []
for d in lv2_index:
    all_list = all_list + list(daily_k200.loc[:, d])

In [23]:
lv2_companies = list(set(all_list))
lv2_companies   # 312개

[nan,
 '현대증권',
 '오뚜기',
 '동양',
 'CJ',
 '쌍용양회',
 '현대모비스',
 '일진머티리얼즈',
 '삼성전자',
 '하이트맥주',
 '대덕GDS',
 '한온시스템',
 '대우조선해양',
 '우리은행',
 '우리금융',
 '코스맥스',
 '한화솔루션',
 '외환은행',
 '두산중공업',
 '크라운해태홀딩스',
 '동아쏘시오홀딩스',
 '미래에셋대우',
 '국도화학',
 '만도',
 '무학',
 '신세계',
 '현대로템',
 '퍼시스',
 '서흥',
 '광동제약',
 '디와이',
 '율촌화학',
 '한국타이어앤테크놀로지',
 'SBS',
 'LG유플러스',
 '부광약품',
 '카프로',
 '삼성화재',
 '신성이엔지',
 '삼성카드',
 '현대상선',
 '알앤엘바이오',
 '제일모직',
 '서연',
 '일신방직',
 '현대제철',
 '한솔케미칼',
 '도레이케미칼',
 '세하',
 '한국금융지주',
 '동부제철',
 '보령제약',
 'LG',
 '삼성전기',
 '디티알오토모티브',
 'STX조선해양',
 '코스맥스비티아이',
 '현대홈쇼핑',
 '동화약품',
 'SK',
 '동원F&B',
 '쌍용차',
 '삼성바이오로직스',
 '신세계인터내셔날',
 '한화화인케미칼',
 '코리아써키트',
 '종근당',
 '대상',
 '대구은행',
 '종근당홀딩스',
 '사조동아원',
 'HDC현대산업개발',
 'NH투자증권',
 '금호전기',
 '롯데쇼핑',
 'HSD엔진',
 '일동홀딩스',
 '삼성중공업',
 '대한제분',
 'NAVER',
 'BGF',
 'LG이노텍',
 '녹십자',
 '메리츠종금증권',
 '포스코플랜텍',
 'DB손해보험',
 '롯데칠성',
 '삼성증권',
 '신도리코',
 '코오롱인더',
 'GS',
 '셀트리온',
 'KT',
 '삼성SDI',
 '일진디스플',
 '한진중공업',
 '현대글로비스',
 '삼진제약',
 'LS',
 '한국철강',
 '한국단자',
 'BGF리테일',
 'CJ CGV',
 '락앤락',
 '케이씨오에너지',
 '오리온홀딩스',
 '효성',
 'LG화학',
 '엔씨소프트',
 'SK하이닉스',
 'KT&G',
 '강원랜드',
 '남해화학',
 '삼성물산',
 '세원셀론텍',
 '제일기획',
 '후성',
 '한국테크놀로지그룹',
 '유한양행',
 'SK텔레콤',
 '하이트진로',
 '현대건설',
 'STX엔진',
 '전기초자',
 '한전기술',
 '한국조선해양',
 '에스엘',
 '무림P&P',
 '아세아',
 '현대그린푸드',
 '롯데하이마트',
 '세종공업',
 '한국카본',
 '금호석유',
 '현대엘리베이',
 'HDC',
 '우리금융지주',
 '대원강업',
 '대림산업',
 '기아차',
 '금호산업',
 '세방전지',
 '동국제강',
 '유니온스틸',
 '제일파마홀딩스',
 '한솔홀딩스',
 '코오롱',
 '한국가스공사',
 '하이트진로홀딩스',
 '빙그레',
 '한국전력',
 'LG생명과학',
 '롯데정밀화학',
 '대한항공',
 '한화에어로스페이스',
 '대우건설',
 '효성중공업',
 '기업은행',
 'SK디스커버리',
 '호텔신라',
 '금호타이어',
 '한미약품',
 'LS산전',
 '한화',
 'KB금융',
 '오리온',
 '삼성생명',
 '인디에프',
 '케이피케미칼',
 'BNK금융지주',
 '유니드',
 'LG상사',
 '자화전자',
 '영원무역',
 '삼양제넥스',
 '부산은행',
 '조선내화',
 '한미사이언스',
 'LG전자',
 '대웅제약',
 '세아제강지주',
 '휠라홀딩스',
 '현대해상',
 'POSCO',
 '대한제당',
 '팜스코',
 '하나금융지주',
 'DB하이텍',
 '현대백화점',
 'STX중공업',
 '포스코인터내셔널',
 '휴켐스',
 '동원시스템즈',
 '한국제지',
 '한솔테크닉스',
 '두산',
 '롯데지주',
 'S-Oil',
 '현대리바트',
 '벽산',
 '휴비스',
 'STX',
 'SK네트웍스',
 '한세실업',
 '일양약품',
 '큐로',
 '모토닉',
 '경방',
 '대한전선',
 'GS건설',
 '영진약품',
 '송원산업',
 '남양유업',
 'LF',
 '조광피혁',
 '한올바이오파마',
 '에이블씨엔씨',
 'SK이노베이션',
 '한국쉘석유',
 '태광산업',
 '영풍',
 'KPX케미칼',
 'S&T모티브',
 '현대하이스코',
 '세아베스틸',
 '현대위아',
 '한일현대시멘트',
 '두산인프라코어',
 'AK홀딩스',
 'OCI',
 '애경산업',
 '삼양홀딩스',
 '아이에스동서',
 '화신',
 '대덕전자',
 '일성신약',
 'GS리테일',
 '넥센타이어',
 '두산밥캣',
 '코웨이',
 '삼영전자',
 'LG디스플레이',
 '대한제강',
 '현대중공업지주',
 '아모레G',
 '아모레퍼시픽',
 '에스원',
 '한섬',
 '엔케이',
 '현대미포조선',
 '한진중공업홀딩스',
 '롯데푸드',
 '신한지주',
 '일진전기',
 '한라홀딩스',
 '동일산업',
 'CJ대한통운',
 '한전KPS',
 '웅진에너지',
 '롯데케미칼',
 '녹십자홀딩스',
 '삼성엔지니어링',
 '유수홀딩스',
 '현대차',
 '이마트',
 '파미셀',
 '광전자',
 'JW홀딩스',
 '고려제강',
 '대교',
 'KC그린홀딩스',
 'LG하우시스',
 '한일홀딩스',
 '이수화학',
 '미래에셋증권',
 '한샘',
 '동서',
 '고려아연',
 '풍산',
 'SK케미칼',
 '농심',
 'DGB금융지주',
 '무림페이퍼',
 '한화생명',
 '동아에스티',
 '한미반도체',
 '한독',
 'LIG넥스원',
 'CJ제일제당',
 'SPC삼립',
 'S&TC',
 'S&T중공업',
 'KCC',
 'SKC',
 '삼양사',
 '이노션',
 'LG생활건강',
 '한국콜마',
 '알루코',
 '한국항공우주',
 'GKL',
 '삼광글라스',
 '한국기술산업',
 '팬오션',
 '대한유화',
 '카카오',
 'JW중외제약',
 'KISCO홀딩스',
 '삼성에스디에스',
 '쿠쿠홀딩스',
 'TBH글로벌',
 '넷마블']

In [24]:
del lv2_companies[0]
lv2_companies = sorted(lv2_companies)   # 순서대로 정렬
lv2_companies   # 311개

['AK홀딩스',
 'BGF',
 'BGF리테일',
 'BNK금융지주',
 'CJ',
 'CJ CGV',
 'CJ대한통운',
 'CJ제일제당',
 'DB손해보험',
 'DB하이텍',
 'DGB금융지주',
 'GKL',
 'GS',
 'GS건설',
 'GS리테일',
 'HDC',
 'HDC현대산업개발',
 'HSD엔진',
 'JW중외제약',
 'JW홀딩스',
 'KB금융',
 'KCC',
 'KC그린홀딩스',
 'KISCO홀딩스',
 'KPX케미칼',
 'KT',
 'KT&G',
 'LF',
 'LG',
 'LG디스플레이',
 'LG상사',
 'LG생명과학',
 'LG생활건강',
 'LG유플러스',
 'LG이노텍',
 'LG전자',
 'LG하우시스',
 'LG화학',
 'LIG넥스원',
 'LS',
 'LS산전',
 'NAVER',
 'NH투자증권',
 'OCI',
 'POSCO',
 'S&TC',
 'S&T모티브',
 'S&T중공업',
 'S-Oil',
 'SBS',
 'SK',
 'SKC',
 'SK네트웍스',
 'SK디스커버리',
 'SK이노베이션',
 'SK케미칼',
 'SK텔레콤',
 'SK하이닉스',
 'SPC삼립',
 'STX',
 'STX엔진',
 'STX조선해양',
 'STX중공업',
 'TBH글로벌',
 '강원랜드',
 '경방',
 '고려아연',
 '고려제강',
 '광동제약',
 '광전자',
 '국도화학',
 '금호산업',
 '금호석유',
 '금호전기',
 '금호타이어',
 '기아차',
 '기업은행',
 '남양유업',
 '남해화학',
 '넥센타이어',
 '넷마블',
 '녹십자',
 '녹십자홀딩스',
 '농심',
 '대교',
 '대구은행',
 '대덕GDS',
 '대덕전자',
 '대림산업',
 '대상',
 '대우건설',
 '대우조선해양',
 '대웅제약',
 '대원강업',
 '대한유화',
 '대한전선',
 '대한제강',
 '대한제당',
 '대한제분',
 '대한항공',
 '도레이케미칼',
 '동국제강',
 '동부제철',
 '동서',
 '동아쏘시오홀딩스',
 '동아에스티',
 '동양',
 '동원F&B',
 '동원시스템즈',
 '동일산업',
 '동화약품',
 '두산',
 '두산밥캣',
 '두산인프라코어',
 '두산중공업',
 '디와이',
 '디티알오토모티브',
 '락앤락',
 '롯데쇼핑',
 '롯데정밀화학',
 '롯데지주',
 '롯데칠성',
 '롯데케미칼',
 '롯데푸드',
 '롯데하이마트',
 '만도',
 '메리츠종금증권',
 '모토닉',
 '무림P&P',
 '무림페이퍼',
 '무학',
 '미래에셋대우',
 '미래에셋증권',
 '벽산',
 '보령제약',
 '부광약품',
 '부산은행',
 '빙그레',
 '사조동아원',
 '삼광글라스',
 '삼성SDI',
 '삼성물산',
 '삼성바이오로직스',
 '삼성생명',
 '삼성에스디에스',
 '삼성엔지니어링',
 '삼성전기',
 '삼성전자',
 '삼성중공업',
 '삼성증권',
 '삼성카드',
 '삼성화재',
 '삼양사',
 '삼양제넥스',
 '삼양홀딩스',
 '삼영전자',
 '삼진제약',
 '서연',
 '서흥',
 '세방전지',
 '세아베스틸',
 '세아제강지주',
 '세원셀론텍',
 '세종공업',
 '세하',
 '셀트리온',
 '송원산업',
 '신도리코',
 '신성이엔지',
 '신세계',
 '신세계인터내셔날',
 '신한지주',
 '쌍용양회',
 '쌍용차',
 '아모레G',
 '아모레퍼시픽',
 '아세아',
 '아이에스동서',
 '알루코',
 '알앤엘바이오',
 '애경산업',
 '에스엘',
 '에스원',
 '에이블씨엔씨',
 '엔씨소프트',
 '엔케이',
 '영원무역',
 '영진약품',
 '영풍',
 '오뚜기',
 '오리온',
 '오리온홀딩스',
 '외환은행',
 '우리금융',
 '우리금융지주',
 '우리은행',
 '웅진에너지',
 '유니드',
 '유니온스틸',
 '유수홀딩스',
 '유한양행',
 '율촌화학',
 '이노션',
 '이마트',
 '이수화학',
 '인디에프',
 '일동홀딩스',
 '일성신약',
 '일신방직',
 '일양약품',
 '일진디스플',
 '일진머티리얼즈',
 '일진전기',
 '자화전자',
 '전기초자',
 '제일기획',
 '제일모직',
 '제일파마홀딩스',
 '조광피혁',
 '조선내화',
 '종근당',
 '종근당홀딩스',
 '카카오',
 '카프로',
 '케이씨오에너지',
 '케이피케미칼',
 '코리아써키트',
 '코스맥스',
 '코스맥스비티아이',
 '코오롱',
 '코오롱인더',
 '코웨이',
 '쿠쿠홀딩스',
 '큐로',
 '크라운해태홀딩스',
 '태광산업',
 '파미셀',
 '팜스코',
 '팬오션',
 '퍼시스',
 '포스코인터내셔널',
 '포스코플랜텍',
 '풍산',
 '하나금융지주',
 '하이트맥주',
 '하이트진로',
 '하이트진로홀딩스',
 '한국가스공사',
 '한국금융지주',
 '한국기술산업',
 '한국단자',
 '한국쉘석유',
 '한국전력',
 '한국제지',
 '한국조선해양',
 '한국철강',
 '한국카본',
 '한국콜마',
 '한국타이어앤테크놀로지',
 '한국테크놀로지그룹',
 '한국항공우주',
 '한독',
 '한라홀딩스',
 '한미반도체',
 '한미사이언스',
 '한미약품',
 '한샘',
 '한섬',
 '한세실업',
 '한솔케미칼',
 '한솔테크닉스',
 '한솔홀딩스',
 '한온시스템',
 '한올바이오파마',
 '한일현대시멘트',
 '한일홀딩스',
 '한전KPS',
 '한전기술',
 '한진중공업',
 '한진중공업홀딩스',
 '한화',
 '한화생명',
 '한화솔루션',
 '한화에어로스페이스',
 '한화화인케미칼',
 '현대건설',
 '현대그린푸드',
 '현대글로비스',
 '현대로템',
 '현대리바트',
 '현대모비스',
 '현대미포조선',
 '현대백화점',
 '현대상선',
 '현대엘리베이',
 '현대위아',
 '현대제철',
 '현대중공업지주',
 '현대증권',
 '현대차',
 '현대하이스코',
 '현대해상',
 '현대홈쇼핑',
 '호텔신라',
 '화신',
 '효성',
 '효성중공업',
 '후성',
 '휠라홀딩스',
 '휴비스',
 '휴켐스']

In [25]:
lv2_companies.index('우리금융지주')

194

In [26]:
del lv2_companies[194]

In [27]:
# Data Guide 상 기업이름(수정하기 전) → symbol_dic이용할 때 써먹을 것
lv2_companies

['AK홀딩스',
 'BGF',
 'BGF리테일',
 'BNK금융지주',
 'CJ',
 'CJ CGV',
 'CJ대한통운',
 'CJ제일제당',
 'DB손해보험',
 'DB하이텍',
 'DGB금융지주',
 'GKL',
 'GS',
 'GS건설',
 'GS리테일',
 'HDC',
 'HDC현대산업개발',
 'HSD엔진',
 'JW중외제약',
 'JW홀딩스',
 'KB금융',
 'KCC',
 'KC그린홀딩스',
 'KISCO홀딩스',
 'KPX케미칼',
 'KT',
 'KT&G',
 'LF',
 'LG',
 'LG디스플레이',
 'LG상사',
 'LG생명과학',
 'LG생활건강',
 'LG유플러스',
 'LG이노텍',
 'LG전자',
 'LG하우시스',
 'LG화학',
 'LIG넥스원',
 'LS',
 'LS산전',
 'NAVER',
 'NH투자증권',
 'OCI',
 'POSCO',
 'S&TC',
 'S&T모티브',
 'S&T중공업',
 'S-Oil',
 'SBS',
 'SK',
 'SKC',
 'SK네트웍스',
 'SK디스커버리',
 'SK이노베이션',
 'SK케미칼',
 'SK텔레콤',
 'SK하이닉스',
 'SPC삼립',
 'STX',
 'STX엔진',
 'STX조선해양',
 'STX중공업',
 'TBH글로벌',
 '강원랜드',
 '경방',
 '고려아연',
 '고려제강',
 '광동제약',
 '광전자',
 '국도화학',
 '금호산업',
 '금호석유',
 '금호전기',
 '금호타이어',
 '기아차',
 '기업은행',
 '남양유업',
 '남해화학',
 '넥센타이어',
 '넷마블',
 '녹십자',
 '녹십자홀딩스',
 '농심',
 '대교',
 '대구은행',
 '대덕GDS',
 '대덕전자',
 '대림산업',
 '대상',
 '대우건설',
 '대우조선해양',
 '대웅제약',
 '대원강업',
 '대한유화',
 '대한전선',
 '대한제강',
 '대한제당',
 '대한제분',
 '대한항공',
 '도레이케미칼',
 '동국제강',
 '동부제철',
 '동서',
 '동아쏘시오홀딩스',
 '동아에스티',
 '동양',
 '동원F&B',
 '동원시스템즈',
 '동일산업',
 '동화약품',
 '두산',
 '두산밥캣',
 '두산인프라코어',
 '두산중공업',
 '디와이',
 '디티알오토모티브',
 '락앤락',
 '롯데쇼핑',
 '롯데정밀화학',
 '롯데지주',
 '롯데칠성',
 '롯데케미칼',
 '롯데푸드',
 '롯데하이마트',
 '만도',
 '메리츠종금증권',
 '모토닉',
 '무림P&P',
 '무림페이퍼',
 '무학',
 '미래에셋대우',
 '미래에셋증권',
 '벽산',
 '보령제약',
 '부광약품',
 '부산은행',
 '빙그레',
 '사조동아원',
 '삼광글라스',
 '삼성SDI',
 '삼성물산',
 '삼성바이오로직스',
 '삼성생명',
 '삼성에스디에스',
 '삼성엔지니어링',
 '삼성전기',
 '삼성전자',
 '삼성중공업',
 '삼성증권',
 '삼성카드',
 '삼성화재',
 '삼양사',
 '삼양제넥스',
 '삼양홀딩스',
 '삼영전자',
 '삼진제약',
 '서연',
 '서흥',
 '세방전지',
 '세아베스틸',
 '세아제강지주',
 '세원셀론텍',
 '세종공업',
 '세하',
 '셀트리온',
 '송원산업',
 '신도리코',
 '신성이엔지',
 '신세계',
 '신세계인터내셔날',
 '신한지주',
 '쌍용양회',
 '쌍용차',
 '아모레G',
 '아모레퍼시픽',
 '아세아',
 '아이에스동서',
 '알루코',
 '알앤엘바이오',
 '애경산업',
 '에스엘',
 '에스원',
 '에이블씨엔씨',
 '엔씨소프트',
 '엔케이',
 '영원무역',
 '영진약품',
 '영풍',
 '오뚜기',
 '오리온',
 '오리온홀딩스',
 '외환은행',
 '우리금융',
 '우리은행',
 '웅진에너지',
 '유니드',
 '유니온스틸',
 '유수홀딩스',
 '유한양행',
 '율촌화학',
 '이노션',
 '이마트',
 '이수화학',
 '인디에프',
 '일동홀딩스',
 '일성신약',
 '일신방직',
 '일양약품',
 '일진디스플',
 '일진머티리얼즈',
 '일진전기',
 '자화전자',
 '전기초자',
 '제일기획',
 '제일모직',
 '제일파마홀딩스',
 '조광피혁',
 '조선내화',
 '종근당',
 '종근당홀딩스',
 '카카오',
 '카프로',
 '케이씨오에너지',
 '케이피케미칼',
 '코리아써키트',
 '코스맥스',
 '코스맥스비티아이',
 '코오롱',
 '코오롱인더',
 '코웨이',
 '쿠쿠홀딩스',
 '큐로',
 '크라운해태홀딩스',
 '태광산업',
 '파미셀',
 '팜스코',
 '팬오션',
 '퍼시스',
 '포스코인터내셔널',
 '포스코플랜텍',
 '풍산',
 '하나금융지주',
 '하이트맥주',
 '하이트진로',
 '하이트진로홀딩스',
 '한국가스공사',
 '한국금융지주',
 '한국기술산업',
 '한국단자',
 '한국쉘석유',
 '한국전력',
 '한국제지',
 '한국조선해양',
 '한국철강',
 '한국카본',
 '한국콜마',
 '한국타이어앤테크놀로지',
 '한국테크놀로지그룹',
 '한국항공우주',
 '한독',
 '한라홀딩스',
 '한미반도체',
 '한미사이언스',
 '한미약품',
 '한샘',
 '한섬',
 '한세실업',
 '한솔케미칼',
 '한솔테크닉스',
 '한솔홀딩스',
 '한온시스템',
 '한올바이오파마',
 '한일현대시멘트',
 '한일홀딩스',
 '한전KPS',
 '한전기술',
 '한진중공업',
 '한진중공업홀딩스',
 '한화',
 '한화생명',
 '한화솔루션',
 '한화에어로스페이스',
 '한화화인케미칼',
 '현대건설',
 '현대그린푸드',
 '현대글로비스',
 '현대로템',
 '현대리바트',
 '현대모비스',
 '현대미포조선',
 '현대백화점',
 '현대상선',
 '현대엘리베이',
 '현대위아',
 '현대제철',
 '현대중공업지주',
 '현대증권',
 '현대차',
 '현대하이스코',
 '현대해상',
 '현대홈쇼핑',
 '호텔신라',
 '화신',
 '효성',
 '효성중공업',
 '후성',
 '휠라홀딩스',
 '휴비스',
 '휴켐스']

In [28]:
len(lv2_companies)

310

In [30]:
for i in range(310):
    if lv2_companies[i] != lv2_companies_rename[i]:
        print(lv2_companies[i], lv2_companies_rename[i])

KCC 케이씨씨
KT 케이티
KT&G 케이티앤지
POSCO 포스코
TBH글로벌 티비에이치글로벌
금호석유 금호석유화학
기아차 기아자동차
롯데칠성 롯데칠성음료
삼성화재 삼성화재해상보험
삼영전자 삼영전자공업
쌍용양회 쌍용양회공업
쌍용차 쌍용자동차
아모레G 아모레퍼시픽그룹
알앤엘바이오 알바이오
외환은행 하나은행
우리금융 우리금융지주
전기초자 한국전기초자
케이씨오에너지 아진카인텍
한국단자 한국단자공업
한국전력 한국전력공사
현대엘리베이 현대엘리베이터
현대증권 케이비증권
현대차 현대자동차

In [21]:
samsung = fdr.DataReader('005930', '2010-01-01', '2019-12-31')
lv2_index_rename = list(samsung.index)
lv2_index_rename

[Timestamp('2010-01-04 00:00:00'),
 Timestamp('2010-01-05 00:00:00'),
 Timestamp('2010-01-06 00:00:00'),
 Timestamp('2010-01-07 00:00:00'),
 Timestamp('2010-01-08 00:00:00'),
 Timestamp('2010-01-11 00:00:00'),
 Timestamp('2010-01-12 00:00:00'),
 Timestamp('2010-01-13 00:00:00'),
 Timestamp('2010-01-14 00:00:00'),
 Timestamp('2010-01-15 00:00:00'),
 Timestamp('2010-01-18 00:00:00'),
 Timestamp('2010-01-19 00:00:00'),
 Timestamp('2010-01-20 00:00:00'),
 Timestamp('2010-01-21 00:00:00'),
 Timestamp('2010-01-22 00:00:00'),
 Timestamp('2010-01-25 00:00:00'),
 Timestamp('2010-01-26 00:00:00'),
 Timestamp('2010-01-27 00:00:00'),
 Timestamp('2010-01-28 00:00:00'),
 Timestamp('2010-01-29 00:00:00'),
 Timestamp('2010-02-01 00:00:00'),
 Timestamp('2010-02-02 00:00:00'),
 Timestamp('2010-02-03 00:00:00'),
 Timestamp('2010-02-04 00:00:00'),
 Timestamp('2010-02-05 00:00:00'),
 Timestamp('2010-02-08 00:00:00'),
 Timestamp('2010-02-09 00:00:00'),
 Timestamp('2010-02-10 00:00:00'),
 Timestamp('2010-02-11 00:00:00'),
 Timestamp('2010-02-12 00:00:00'),
 Timestamp('2010-02-16 00:00:00'),
 Timestamp('2010-02-17 00:00:00'),
 Timestamp('2010-02-18 00:00:00'),
 Timestamp('2010-02-19 00:00:00'),
 Timestamp('2010-02-22 00:00:00'),
 Timestamp('2010-02-23 00:00:00'),
 Timestamp('2010-02-24 00:00:00'),
 Timestamp('2010-02-25 00:00:00'),
 Timestamp('2010-02-26 00:00:00'),
 Timestamp('2010-03-02 00:00:00'),
 Timestamp('2010-03-03 00:00:00'),
 Timestamp('2010-03-04 00:00:00'),
 Timestamp('2010-03-05 00:00:00'),
 Timestamp('2010-03-08 00:00:00'),
 Timestamp('2010-03-09 00:00:00'),
 Timestamp('2010-03-10 00:00:00'),
 Timestamp('2010-03-11 00:00:00'),
 Timestamp('2010-03-12 00:00:00'),
 Timestamp('2010-03-15 00:00:00'),
 Timestamp('2010-03-16 00:00:00'),
 Timestamp('2010-03-17 00:00:00'),
 Timestamp('2010-03-18 00:00:00'),
 Timestamp('2010-03-19 00:00:00'),
 Timestamp('2010-03-22 00:00:00'),
 Timestamp('2010-03-23 00:00:00'),
 Timestamp('2010-03-24 00:00:00'),
 Timestamp('2010-03-25 00:00:00'),
 Timestamp('2010-03-26 00:00:00'),
 Timestamp('2010-03-29 00:00:00'),
 Timestamp('2010-03-30 00:00:00'),
 Timestamp('2010-03-31 00:00:00'),
 Timestamp('2010-04-01 00:00:00'),
 Timestamp('2010-04-02 00:00:00'),
 Timestamp('2010-04-05 00:00:00'),
 Timestamp('2010-04-06 00:00:00'),
 Timestamp('2010-04-07 00:00:00'),
 Timestamp('2010-04-08 00:00:00'),
 Timestamp('2010-04-09 00:00:00'),
 Timestamp('2010-04-12 00:00:00'),
 Timestamp('2010-04-13 00:00:00'),
 Timestamp('2010-04-14 00:00:00'),
 Timestamp('2010-04-15 00:00:00'),
 Timestamp('2010-04-16 00:00:00'),
 Timestamp('2010-04-19 00:00:00'),
 Timestamp('2010-04-20 00:00:00'),
 Timestamp('2010-04-21 00:00:00'),
 Timestamp('2010-04-22 00:00:00'),
 Timestamp('2010-04-23 00:00:00'),
 Timestamp('2010-04-26 00:00:00'),
 Timestamp('2010-04-27 00:00:00'),
 Timestamp('2010-04-28 00:00:00'),
 Timestamp('2010-04-29 00:00:00'),
 Timestamp('2010-04-30 00:00:00'),
 Timestamp('2010-05-03 00:00:00'),
 Timestamp('2010-05-04 00:00:00'),
 Timestamp('2010-05-06 00:00:00'),
 Timestamp('2010-05-07 00:00:00'),
 Timestamp('2010-05-10 00:00:00'),
 Timestamp('2010-05-11 00:00:00'),
 Timestamp('2010-05-12 00:00:00'),
 Timestamp('2010-05-13 00:00:00'),
 Timestamp('2010-05-14 00:00:00'),
 Timestamp('2010-05-17 00:00:00'),
 Timestamp('2010-05-18 00:00:00'),
 Timestamp('2010-05-19 00:00:00'),
 Timestamp('2010-05-20 00:00:00'),
 Timestamp('2010-05-24 00:00:00'),
 Timestamp('2010-05-25 00:00:00'),
 Timestamp('2010-05-26 00:00:00'),
 Timestamp('2010-05-27 00:00:00'),
 Timestamp('2010-05-28 00:00:00'),
 Timestamp('2010-05-31 00:00:00'),
 Timestamp('2010-06-01 00:00:00'),
 Timestamp('2010-06-03 00:00:00'),
 Timestamp('2010-06-04 00:00:00'),
 Timestamp('2010-06-07 00:00:00'),
 Timestamp('2010-06-08 00:00:00'),
 Timestamp('2010-06-09 00:00:00'),
 Timestamp('2010-06-10 00:00:00'),
 Timestamp('2010-06-11 00:00:00'),
 Timestamp('2010-06-14 00:00:00'),
 Timestamp('2010-06-15 00:00:00'),
 Timestamp('2010-06-16 00:00:00'),
 Timestamp('2010-06-17 00:00:00'),
 Timestamp('2010-06-18 00:00:00'),
 Timestamp('2010-06-21 00:00:00'),
 Timestamp('2010-06-22 00:00:00'),
 Timestamp('2010-06-23 00:00:00'),
 Timestamp('2010-06-24 00:00:00'),
 Timestamp('2010-06-25 00:00:00'),
 Timestamp('2010-06-28 00:00:00'),
 Timestamp('2010-06-29 00:00:00'),
 Timestamp('2010-06-30 00:00:00'),
 Timestamp('2010-07-01 00:00:00'),
 Timestamp('2010-07-02 00:00:00'),
 Timestamp('2010-07-05 00:00:00'),
 Timestamp('2010-07-06 00:00:00'),
 Timestamp('2010-07-07 00:00:00'),
 Timestamp('2010-07-08 00:00:00'),
 Timestamp('2010-07-09 00:00:00'),
 Timestamp('2010-07-12 00:00:00'),
 Timestamp('2010-07-13 00:00:00'),
 Timestamp('2010-07-14 00:00:00'),
 Timestamp('2010-07-15 00:00:00'),
 Timestamp('2010-07-16 00:00:00'),
 Timestamp('2010-07-19 00:00:00'),
 Timestamp('2010-07-20 00:00:00'),
 Timestamp('2010-07-21 00:00:00'),
 Timestamp('2010-07-22 00:00:00'),
 Timestamp('2010-07-23 00:00:00'),
 Timestamp('2010-07-26 00:00:00'),
 Timestamp('2010-07-27 00:00:00'),
 Timestamp('2010-07-28 00:00:00'),
 Timestamp('2010-07-29 00:00:00'),
 Timestamp('2010-07-30 00:00:00'),
 Timestamp('2010-08-02 00:00:00'),
 Timestamp('2010-08-03 00:00:00'),
 Timestamp('2010-08-04 00:00:00'),
 Timestamp('2010-08-05 00:00:00'),
 Timestamp('2010-08-06 00:00:00'),
 Timestamp('2010-08-09 00:00:00'),
 Timestamp('2010-08-10 00:00:00'),
 Timestamp('2010-08-11 00:00:00'),
 Timestamp('2010-08-12 00:00:00'),
 Timestamp('2010-08-13 00:00:00'),
 Timestamp('2010-08-16 00:00:00'),
 Timestamp('2010-08-17 00:00:00'),
 Timestamp('2010-08-18 00:00:00'),
 Timestamp('2010-08-19 00:00:00'),
 Timestamp('2010-08-20 00:00:00'),
 Timestamp('2010-08-23 00:00:00'),
 Timestamp('2010-08-24 00:00:00'),
 Timestamp('2010-08-25 00:00:00'),
 Timestamp('2010-08-26 00:00:00'),
 Timestamp('2010-08-27 00:00:00'),
 Timestamp('2010-08-30 00:00:00'),
 Timestamp('2010-08-31 00:00:00'),
 Timestamp('2010-09-01 00:00:00'),
 Timestamp('2010-09-02 00:00:00'),
 Timestamp('2010-09-03 00:00:00'),
 Timestamp('2010-09-06 00:00:00'),
 Timestamp('2010-09-07 00:00:00'),
 Timestamp('2010-09-08 00:00:00'),
 Timestamp('2010-09-09 00:00:00'),
 Timestamp('2010-09-10 00:00:00'),
 Timestamp('2010-09-13 00:00:00'),
 Timestamp('2010-09-14 00:00:00'),
 Timestamp('2010-09-15 00:00:00'),
 Timestamp('2010-09-16 00:00:00'),
 Timestamp('2010-09-17 00:00:00'),
 Timestamp('2010-09-20 00:00:00'),
 Timestamp('2010-09-24 00:00:00'),
 Timestamp('2010-09-27 00:00:00'),
 Timestamp('2010-09-28 00:00:00'),
 Timestamp('2010-09-29 00:00:00'),
 Timestamp('2010-09-30 00:00:00'),
 Timestamp('2010-10-01 00:00:00'),
 Timestamp('2010-10-04 00:00:00'),
 Timestamp('2010-10-05 00:00:00'),
 Timestamp('2010-10-06 00:00:00'),
 Timestamp('2010-10-07 00:00:00'),
 Timestamp('2010-10-08 00:00:00'),
 Timestamp('2010-10-11 00:00:00'),
 Timestamp('2010-10-12 00:00:00'),
 Timestamp('2010-10-13 00:00:00'),
 Timestamp('2010-10-14 00:00:00'),
 Timestamp('2010-10-15 00:00:00'),
 Timestamp('2010-10-18 00:00:00'),
 Timestamp('2010-10-19 00:00:00'),
 Timestamp('2010-10-20 00:00:00'),
 Timestamp('2010-10-21 00:00:00'),
 Timestamp('2010-10-22 00:00:00'),
 Timestamp('2010-10-25 00:00:00'),
 Timestamp('2010-10-26 00:00:00'),
 Timestamp('2010-10-27 00:00:00'),
 Timestamp('2010-10-28 00:00:00'),
 Timestamp('2010-10-29 00:00:00'),
 Timestamp('2010-11-01 00:00:00'),
 Timestamp('2010-11-02 00:00:00'),
 Timestamp('2010-11-03 00:00:00'),
 Timestamp('2010-11-04 00:00:00'),
 Timestamp('2010-11-05 00:00:00'),
 Timestamp('2010-11-08 00:00:00'),
 Timestamp('2010-11-09 00:00:00'),
 Timestamp('2010-11-10 00:00:00'),
 Timestamp('2010-11-11 00:00:00'),
 Timestamp('2010-11-12 00:00:00'),
 Timestamp('2010-11-15 00:00:00'),
 Timestamp('2010-11-16 00:00:00'),
 Timestamp('2010-11-17 00:00:00'),
 Timestamp('2010-11-18 00:00:00'),
 Timestamp('2010-11-19 00:00:00'),
 Timestamp('2010-11-22 00:00:00'),
 Timestamp('2010-11-23 00:00:00'),
 Timestamp('2010-11-24 00:00:00'),
 Timestamp('2010-11-25 00:00:00'),
 Timestamp('2010-11-26 00:00:00'),
 Timestamp('2010-11-29 00:00:00'),
 Timestamp('2010-11-30 00:00:00'),
 Timestamp('2010-12-01 00:00:00'),
 Timestamp('2010-12-02 00:00:00'),
 Timestamp('2010-12-03 00:00:00'),
 Timestamp('2010-12-06 00:00:00'),
 Timestamp('2010-12-07 00:00:00'),
 Timestamp('2010-12-08 00:00:00'),
 Timestamp('2010-12-09 00:00:00'),
 Timestamp('2010-12-10 00:00:00'),
 Timestamp('2010-12-13 00:00:00'),
 Timestamp('2010-12-14 00:00:00'),
 Timestamp('2010-12-15 00:00:00'),
 Timestamp('2010-12-16 00:00:00'),
 Timestamp('2010-12-17 00:00:00'),
 Timestamp('2010-12-20 00:00:00'),
 Timestamp('2010-12-21 00:00:00'),
 Timestamp('2010-12-22 00:00:00'),
 Timestamp('2010-12-23 00:00:00'),
 Timestamp('2010-12-24 00:00:00'),
 Timestamp('2010-12-27 00:00:00'),
 Timestamp('2010-12-28 00:00:00'),
 Timestamp('2010-12-29 00:00:00'),
 Timestamp('2010-12-30 00:00:00'),
 Timestamp('2011-01-03 00:00:00'),
 Timestamp('2011-01-04 00:00:00'),
 Timestamp('2011-01-05 00:00:00'),
 Timestamp('2011-01-06 00:00:00'),
 Timestamp('2011-01-07 00:00:00'),
 Timestamp('2011-01-10 00:00:00'),
 Timestamp('2011-01-11 00:00:00'),
 Timestamp('2011-01-12 00:00:00'),
 Timestamp('2011-01-13 00:00:00'),
 Timestamp('2011-01-14 00:00:00'),
 Timestamp('2011-01-17 00:00:00'),
 Timestamp('2011-01-18 00:00:00'),
 Timestamp('2011-01-19 00:00:00'),
 Timestamp('2011-01-20 00:00:00'),
 Timestamp('2011-01-21 00:00:00'),
 Timestamp('2011-01-24 00:00:00'),
 Timestamp('2011-01-25 00:00:00'),
 Timestamp('2011-01-26 00:00:00'),
 Timestamp('2011-01-27 00:00:00'),
 Timestamp('2011-01-28 00:00:00'),
 Timestamp('2011-01-31 00:00:00'),
 Timestamp('2011-02-01 00:00:00'),
 Timestamp('2011-02-07 00:00:00'),
 Timestamp('2011-02-08 00:00:00'),
 Timestamp('2011-02-09 00:00:00'),
 Timestamp('2011-02-10 00:00:00'),
 Timestamp('2011-02-11 00:00:00'),
 Timestamp('2011-02-14 00:00:00'),
 Timestamp('2011-02-15 00:00:00'),
 Timestamp('2011-02-16 00:00:00'),
 Timestamp('2011-02-17 00:00:00'),
 Timestamp('2011-02-18 00:00:00'),
 Timestamp('2011-02-21 00:00:00'),
 Timestamp('2011-02-22 00:00:00'),
 Timestamp('2011-02-23 00:00:00'),
 Timestamp('2011-02-24 00:00:00'),
 Timestamp('2011-02-25 00:00:00'),
 Timestamp('2011-02-28 00:00:00'),
 Timestamp('2011-03-02 00:00:00'),
 Timestamp('2011-03-03 00:00:00'),
 Timestamp('2011-03-04 00:00:00'),
 Timestamp('2011-03-07 00:00:00'),
 Timestamp('2011-03-08 00:00:00'),
 Timestamp('2011-03-09 00:00:00'),
 Timestamp('2011-03-10 00:00:00'),
 Timestamp('2011-03-11 00:00:00'),
 Timestamp('2011-03-14 00:00:00'),
 Timestamp('2011-03-15 00:00:00'),
 Timestamp('2011-03-16 00:00:00'),
 Timestamp('2011-03-17 00:00:00'),
 Timestamp('2011-03-18 00:00:00'),
 Timestamp('2011-03-21 00:00:00'),
 Timestamp('2011-03-22 00:00:00'),
 Timestamp('2011-03-23 00:00:00'),
 Timestamp('2011-03-24 00:00:00'),
 Timestamp('2011-03-25 00:00:00'),
 Timestamp('2011-03-28 00:00:00'),
 Timestamp('2011-03-29 00:00:00'),
 Timestamp('2011-03-30 00:00:00'),
 Timestamp('2011-03-31 00:00:00'),
 Timestamp('2011-04-01 00:00:00'),
 Timestamp('2011-04-04 00:00:00'),
 Timestamp('2011-04-05 00:00:00'),
 Timestamp('2011-04-06 00:00:00'),
 Timestamp('2011-04-07 00:00:00'),
 Timestamp('2011-04-08 00:00:00'),
 Timestamp('2011-04-11 00:00:00'),
 Timestamp('2011-04-12 00:00:00'),
 Timestamp('2011-04-13 00:00:00'),
 Timestamp('2011-04-14 00:00:00'),
 Timestamp('2011-04-15 00:00:00'),
 Timestamp('2011-04-18 00:00:00'),
 Timestamp('2011-04-19 00:00:00'),
 Timestamp('2011-04-20 00:00:00'),
 Timestamp('2011-04-21 00:00:00'),
 Timestamp('2011-04-22 00:00:00'),
 Timestamp('2011-04-25 00:00:00'),
 Timestamp('2011-04-26 00:00:00'),
 Timestamp('2011-04-27 00:00:00'),
 Timestamp('2011-04-28 00:00:00'),
 Timestamp('2011-04-29 00:00:00'),
 Timestamp('2011-05-02 00:00:00'),
 Timestamp('2011-05-03 00:00:00'),
 Timestamp('2011-05-04 00:00:00'),
 Timestamp('2011-05-06 00:00:00'),
 Timestamp('2011-05-09 00:00:00'),
 Timestamp('2011-05-11 00:00:00'),
 Timestamp('2011-05-12 00:00:00'),
 Timestamp('2011-05-13 00:00:00'),
 Timestamp('2011-05-16 00:00:00'),
 Timestamp('2011-05-17 00:00:00'),
 Timestamp('2011-05-18 00:00:00'),
 Timestamp('2011-05-19 00:00:00'),
 Timestamp('2011-05-20 00:00:00'),
 Timestamp('2011-05-23 00:00:00'),
 Timestamp('2011-05-24 00:00:00'),
 Timestamp('2011-05-25 00:00:00'),
 Timestamp('2011-05-26 00:00:00'),
 Timestamp('2011-05-27 00:00:00'),
 Timestamp('2011-05-30 00:00:00'),
 Timestamp('2011-05-31 00:00:00'),
 Timestamp('2011-06-01 00:00:00'),
 Timestamp('2011-06-02 00:00:00'),
 Timestamp('2011-06-03 00:00:00'),
 Timestamp('2011-06-07 00:00:00'),
 Timestamp('2011-06-08 00:00:00'),
 Timestamp('2011-06-09 00:00:00'),
 Timestamp('2011-06-10 00:00:00'),
 Timestamp('2011-06-13 00:00:00'),
 Timestamp('2011-06-14 00:00:00'),
 Timestamp('2011-06-15 00:00:00'),
 Timestamp('2011-06-16 00:00:00'),
 Timestamp('2011-06-17 00:00:00'),
 Timestamp('2011-06-20 00:00:00'),
 Timestamp('2011-06-21 00:00:00'),
 Timestamp('2011-06-22 00:00:00'),
 Timestamp('2011-06-23 00:00:00'),
 Timestamp('2011-06-24 00:00:00'),
 Timestamp('2011-06-27 00:00:00'),
 Timestamp('2011-06-28 00:00:00'),
 Timestamp('2011-06-29 00:00:00'),
 Timestamp('2011-06-30 00:00:00'),
 Timestamp('2011-07-01 00:00:00'),
 Timestamp('2011-07-04 00:00:00'),
 Timestamp('2011-07-05 00:00:00'),
 Timestamp('2011-07-06 00:00:00'),
 Timestamp('2011-07-07 00:00:00'),
 Timestamp('2011-07-08 00:00:00'),
 Timestamp('2011-07-11 00:00:00'),
 Timestamp('2011-07-12 00:00:00'),
 Timestamp('2011-07-13 00:00:00'),
 Timestamp('2011-07-14 00:00:00'),
 Timestamp('2011-07-15 00:00:00'),
 Timestamp('2011-07-18 00:00:00'),
 Timestamp('2011-07-19 00:00:00'),
 Timestamp('2011-07-20 00:00:00'),
 Timestamp('2011-07-21 00:00:00'),
 Timestamp('2011-07-22 00:00:00'),
 Timestamp('2011-07-25 00:00:00'),
 Timestamp('2011-07-26 00:00:00'),
 Timestamp('2011-07-27 00:00:00'),
 Timestamp('2011-07-28 00:00:00'),
 Timestamp('2011-07-29 00:00:00'),
 Timestamp('2011-08-01 00:00:00'),
 Timestamp('2011-08-02 00:00:00'),
 Timestamp('2011-08-03 00:00:00'),
 Timestamp('2011-08-04 00:00:00'),
 Timestamp('2011-08-05 00:00:00'),
 Timestamp('2011-08-08 00:00:00'),
 Timestamp('2011-08-09 00:00:00'),
 Timestamp('2011-08-10 00:00:00'),
 Timestamp('2011-08-11 00:00:00'),
 Timestamp('2011-08-12 00:00:00'),
 Timestamp('2011-08-16 00:00:00'),
 Timestamp('2011-08-17 00:00:00'),
 Timestamp('2011-08-18 00:00:00'),
 Timestamp('2011-08-19 00:00:00'),
 Timestamp('2011-08-22 00:00:00'),
 Timestamp('2011-08-23 00:00:00'),
 Timestamp('2011-08-24 00:00:00'),
 Timestamp('2011-08-25 00:00:00'),
 Timestamp('2011-08-26 00:00:00'),
 Timestamp('2011-08-29 00:00:00'),
 Timestamp('2011-08-30 00:00:00'),
 Timestamp('2011-08-31 00:00:00'),
 Timestamp('2011-09-01 00:00:00'),
 Timestamp('2011-09-02 00:00:00'),
 Timestamp('2011-09-05 00:00:00'),
 Timestamp('2011-09-06 00:00:00'),
 Timestamp('2011-09-07 00:00:00'),
 Timestamp('2011-09-08 00:00:00'),
 Timestamp('2011-09-09 00:00:00'),
 Timestamp('2011-09-14 00:00:00'),
 Timestamp('2011-09-15 00:00:00'),
 Timestamp('2011-09-16 00:00:00'),
 Timestamp('2011-09-19 00:00:00'),
 Timestamp('2011-09-20 00:00:00'),
 Timestamp('2011-09-21 00:00:00'),
 Timestamp('2011-09-22 00:00:00'),
 Timestamp('2011-09-23 00:00:00'),
 Timestamp('2011-09-26 00:00:00'),
 Timestamp('2011-09-27 00:00:00'),
 Timestamp('2011-09-28 00:00:00'),
 Timestamp('2011-09-29 00:00:00'),
 Timestamp('2011-09-30 00:00:00'),
 Timestamp('2011-10-04 00:00:00'),
 Timestamp('2011-10-05 00:00:00'),
 Timestamp('2011-10-06 00:00:00'),
 Timestamp('2011-10-07 00:00:00'),
 Timestamp('2011-10-10 00:00:00'),
 Timestamp('2011-10-11 00:00:00'),
 Timestamp('2011-10-12 00:00:00'),
 Timestamp('2011-10-13 00:00:00'),
 Timestamp('2011-10-14 00:00:00'),
 Timestamp('2011-10-17 00:00:00'),
 Timestamp('2011-10-18 00:00:00'),
 Timestamp('2011-10-19 00:00:00'),
 Timestamp('2011-10-20 00:00:00'),
 Timestamp('2011-10-21 00:00:00'),
 Timestamp('2011-10-24 00:00:00'),
 Timestamp('2011-10-25 00:00:00'),
 Timestamp('2011-10-26 00:00:00'),
 Timestamp('2011-10-27 00:00:00'),
 Timestamp('2011-10-28 00:00:00'),
 Timestamp('2011-10-31 00:00:00'),
 Timestamp('2011-11-01 00:00:00'),
 Timestamp('2011-11-02 00:00:00'),
 Timestamp('2011-11-03 00:00:00'),
 Timestamp('2011-11-04 00:00:00'),
 Timestamp('2011-11-07 00:00:00'),
 Timestamp('2011-11-08 00:00:00'),
 Timestamp('2011-11-09 00:00:00'),
 Timestamp('2011-11-10 00:00:00'),
 Timestamp('2011-11-11 00:00:00'),
 Timestamp('2011-11-14 00:00:00'),
 Timestamp('2011-11-15 00:00:00'),
 Timestamp('2011-11-16 00:00:00'),
 Timestamp('2011-11-17 00:00:00'),
 Timestamp('2011-11-18 00:00:00'),
 Timestamp('2011-11-21 00:00:00'),
 Timestamp('2011-11-22 00:00:00'),
 Timestamp('2011-11-23 00:00:00'),
 Timestamp('2011-11-24 00:00:00'),
 Timestamp('2011-11-25 00:00:00'),
 Timestamp('2011-11-28 00:00:00'),
 Timestamp('2011-11-29 00:00:00'),
 Timestamp('2011-11-30 00:00:00'),
 Timestamp('2011-12-01 00:00:00'),
 Timestamp('2011-12-02 00:00:00'),
 Timestamp('2011-12-05 00:00:00'),
 Timestamp('2011-12-06 00:00:00'),
 Timestamp('2011-12-07 00:00:00'),
 Timestamp('2011-12-08 00:00:00'),
 Timestamp('2011-12-09 00:00:00'),
 Timestamp('2011-12-12 00:00:00'),
 Timestamp('2011-12-13 00:00:00'),
 Timestamp('2011-12-14 00:00:00'),
 Timestamp('2011-12-15 00:00:00'),
 Timestamp('2011-12-16 00:00:00'),
 Timestamp('2011-12-19 00:00:00'),
 Timestamp('2011-12-20 00:00:00'),
 Timestamp('2011-12-21 00:00:00'),
 Timestamp('2011-12-22 00:00:00'),
 Timestamp('2011-12-23 00:00:00'),
 Timestamp('2011-12-26 00:00:00'),
 Timestamp('2011-12-27 00:00:00'),
 Timestamp('2011-12-28 00:00:00'),
 Timestamp('2011-12-29 00:00:00'),
 Timestamp('2012-01-02 00:00:00'),
 Timestamp('2012-01-03 00:00:00'),
 Timestamp('2012-01-04 00:00:00'),
 Timestamp('2012-01-05 00:00:00'),
 Timestamp('2012-01-06 00:00:00'),
 Timestamp('2012-01-09 00:00:00'),
 Timestamp('2012-01-10 00:00:00'),
 Timestamp('2012-01-11 00:00:00'),
 Timestamp('2012-01-12 00:00:00'),
 Timestamp('2012-01-13 00:00:00'),
 Timestamp('2012-01-16 00:00:00'),
 Timestamp('2012-01-17 00:00:00'),
 Timestamp('2012-01-18 00:00:00'),
 Timestamp('2012-01-19 00:00:00'),
 Timestamp('2012-01-20 00:00:00'),
 Timestamp('2012-01-25 00:00:00'),
 Timestamp('2012-01-26 00:00:00'),
 Timestamp('2012-01-27 00:00:00'),
 Timestamp('2012-01-30 00:00:00'),
 Timestamp('2012-01-31 00:00:00'),
 Timestamp('2012-02-01 00:00:00'),
 Timestamp('2012-02-02 00:00:00'),
 Timestamp('2012-02-03 00:00:00'),
 Timestamp('2012-02-06 00:00:00'),
 Timestamp('2012-02-07 00:00:00'),
 Timestamp('2012-02-08 00:00:00'),
 Timestamp('2012-02-09 00:00:00'),
 Timestamp('2012-02-10 00:00:00'),
 Timestamp('2012-02-13 00:00:00'),
 Timestamp('2012-02-14 00:00:00'),
 Timestamp('2012-02-15 00:00:00'),
 Timestamp('2012-02-16 00:00:00'),
 Timestamp('2012-02-17 00:00:00'),
 Timestamp('2012-02-20 00:00:00'),
 Timestamp('2012-02-21 00:00:00'),
 Timestamp('2012-02-22 00:00:00'),
 Timestamp('2012-02-23 00:00:00'),
 Timestamp('2012-02-24 00:00:00'),
 Timestamp('2012-02-27 00:00:00'),
 Timestamp('2012-02-28 00:00:00'),
 Timestamp('2012-02-29 00:00:00'),
 Timestamp('2012-03-02 00:00:00'),
 Timestamp('2012-03-05 00:00:00'),
 Timestamp('2012-03-06 00:00:00'),
 Timestamp('2012-03-07 00:00:00'),
 Timestamp('2012-03-08 00:00:00'),
 Timestamp('2012-03-09 00:00:00'),
 Timestamp('2012-03-12 00:00:00'),
 Timestamp('2012-03-13 00:00:00'),
 Timestamp('2012-03-14 00:00:00'),
 Timestamp('2012-03-15 00:00:00'),
 Timestamp('2012-03-16 00:00:00'),
 Timestamp('2012-03-19 00:00:00'),
 Timestamp('2012-03-20 00:00:00'),
 Timestamp('2012-03-21 00:00:00'),
 Timestamp('2012-03-22 00:00:00'),
 Timestamp('2012-03-23 00:00:00'),
 Timestamp('2012-03-26 00:00:00'),
 Timestamp('2012-03-27 00:00:00'),
 Timestamp('2012-03-28 00:00:00'),
 Timestamp('2012-03-29 00:00:00'),
 Timestamp('2012-03-30 00:00:00'),
 Timestamp('2012-04-02 00:00:00'),
 Timestamp('2012-04-03 00:00:00'),
 Timestamp('2012-04-04 00:00:00'),
 Timestamp('2012-04-05 00:00:00'),
 Timestamp('2012-04-06 00:00:00'),
 Timestamp('2012-04-09 00:00:00'),
 Timestamp('2012-04-10 00:00:00'),
 Timestamp('2012-04-12 00:00:00'),
 Timestamp('2012-04-13 00:00:00'),
 Timestamp('2012-04-16 00:00:00'),

In [22]:
def length_adjust(str_) : 
    return (2-len(str_)) * '0' + str_

def date_convertor(date) : 
    year = length_adjust(str(date.year))
    month = length_adjust(str(date.month))
    day = length_adjust(str(date.day))
    yyyymmdd = int(year+month+day)
    return yyyymmdd

In [23]:
lv2_index_rename = list(map(date_convertor,lv2_index_rename))

In [24]:
lv2_index_rename = list(map(str, lv2_index_rename))
lv2_index_rename

['20100104',
 '20100105',
 '20100106',
 '20100107',
 '20100108',
 '20100111',
 '20100112',
 '20100113',
 '20100114',
 '20100115',
 '20100118',
 '20100119',
 '20100120',
 '20100121',
 '20100122',
 '20100125',
 '20100126',
 '20100127',
 '20100128',
 '20100129',
 '20100201',
 '20100202',
 '20100203',
 '20100204',
 '20100205',
 '20100208',
 '20100209',
 '20100210',
 '20100211',
 '20100212',
 '20100216',
 '20100217',
 '20100218',
 '20100219',
 '20100222',
 '20100223',
 '20100224',
 '20100225',
 '20100226',
 '20100302',
 '20100303',
 '20100304',
 '20100305',
 '20100308',
 '20100309',
 '20100310',
 '20100311',
 '20100312',
 '20100315',
 '20100316',
 '20100317',
 '20100318',
 '20100319',
 '20100322',
 '20100323',
 '20100324',
 '20100325',
 '20100326',
 '20100329',
 '20100330',
 '20100331',
 '20100401',
 '20100402',
 '20100405',
 '20100406',
 '20100407',
 '20100408',
 '20100409',
 '20100412',
 '20100413',
 '20100414',
 '20100415',
 '20100416',
 '20100419',
 '20100420',
 '20100421',
 '20100422',
 '20100423',
 '20100426',
 '20100427',
 '20100428',
 '20100429',
 '20100430',
 '20100503',
 '20100504',
 '20100506',
 '20100507',
 '20100510',
 '20100511',
 '20100512',
 '20100513',
 '20100514',
 '20100517',
 '20100518',
 '20100519',
 '20100520',
 '20100524',
 '20100525',
 '20100526',
 '20100527',
 '20100528',
 '20100531',
 '20100601',
 '20100603',
 '20100604',
 '20100607',
 '20100608',
 '20100609',
 '20100610',
 '20100611',
 '20100614',
 '20100615',
 '20100616',
 '20100617',
 '20100618',
 '20100621',
 '20100622',
 '20100623',
 '20100624',
 '20100625',
 '20100628',
 '20100629',
 '20100630',
 '20100701',
 '20100702',
 '20100705',
 '20100706',
 '20100707',
 '20100708',
 '20100709',
 '20100712',
 '20100713',
 '20100714',
 '20100715',
 '20100716',
 '20100719',
 '20100720',
 '20100721',
 '20100722',
 '20100723',
 '20100726',
 '20100727',
 '20100728',
 '20100729',
 '20100730',
 '20100802',
 '20100803',
 '20100804',
 '20100805',
 '20100806',
 '20100809',
 '20100810',
 '20100811',
 '20100812',
 '20100813',
 '20100816',
 '20100817',
 '20100818',
 '20100819',
 '20100820',
 '20100823',
 '20100824',
 '20100825',
 '20100826',
 '20100827',
 '20100830',
 '20100831',
 '20100901',
 '20100902',
 '20100903',
 '20100906',
 '20100907',
 '20100908',
 '20100909',
 '20100910',
 '20100913',
 '20100914',
 '20100915',
 '20100916',
 '20100917',
 '20100920',
 '20100924',
 '20100927',
 '20100928',
 '20100929',
 '20100930',
 '20101001',
 '20101004',
 '20101005',
 '20101006',
 '20101007',
 '20101008',
 '20101011',
 '20101012',
 '20101013',
 '20101014',
 '20101015',
 '20101018',
 '20101019',
 '20101020',
 '20101021',
 '20101022',
 '20101025',
 '20101026',
 '20101027',
 '20101028',
 '20101029',
 '20101101',
 '20101102',
 '20101103',
 '20101104',
 '20101105',
 '20101108',
 '20101109',
 '20101110',
 '20101111',
 '20101112',
 '20101115',
 '20101116',
 '20101117',
 '20101118',
 '20101119',
 '20101122',
 '20101123',
 '20101124',
 '20101125',
 '20101126',
 '20101129',
 '20101130',
 '20101201',
 '20101202',
 '20101203',
 '20101206',
 '20101207',
 '20101208',
 '20101209',
 '20101210',
 '20101213',
 '20101214',
 '20101215',
 '20101216',
 '20101217',
 '20101220',
 '20101221',
 '20101222',
 '20101223',
 '20101224',
 '20101227',
 '20101228',
 '20101229',
 '20101230',
 '20110103',
 '20110104',
 '20110105',
 '20110106',
 '20110107',
 '20110110',
 '20110111',
 '20110112',
 '20110113',
 '20110114',
 '20110117',
 '20110118',
 '20110119',
 '20110120',
 '20110121',
 '20110124',
 '20110125',
 '20110126',
 '20110127',
 '20110128',
 '20110131',
 '20110201',
 '20110207',
 '20110208',
 '20110209',
 '20110210',
 '20110211',
 '20110214',
 '20110215',
 '20110216',
 '20110217',
 '20110218',
 '20110221',
 '20110222',
 '20110223',
 '20110224',
 '20110225',
 '20110228',
 '20110302',
 '20110303',
 '20110304',
 '20110307',
 '20110308',
 '20110309',
 '20110310',
 '20110311',
 '20110314',
 '20110315',
 '20110316',
 '20110317',
 '20110318',
 '20110321',
 '20110322',
 '20110323',
 '20110324',
 '20110325',
 '20110328',
 '20110329',
 '20110330',
 '20110331',
 '20110401',
 '20110404',
 '20110405',
 '20110406',
 '20110407',
 '20110408',
 '20110411',
 '20110412',
 '20110413',
 '20110414',
 '20110415',
 '20110418',
 '20110419',
 '20110420',
 '20110421',
 '20110422',
 '20110425',
 '20110426',
 '20110427',
 '20110428',
 '20110429',
 '20110502',
 '20110503',
 '20110504',
 '20110506',
 '20110509',
 '20110511',
 '20110512',
 '20110513',
 '20110516',
 '20110517',
 '20110518',
 '20110519',
 '20110520',
 '20110523',
 '20110524',
 '20110525',
 '20110526',
 '20110527',
 '20110530',
 '20110531',
 '20110601',
 '20110602',
 '20110603',
 '20110607',
 '20110608',
 '20110609',
 '20110610',
 '20110613',
 '20110614',
 '20110615',
 '20110616',
 '20110617',
 '20110620',
 '20110621',
 '20110622',
 '20110623',
 '20110624',
 '20110627',
 '20110628',
 '20110629',
 '20110630',
 '20110701',
 '20110704',
 '20110705',
 '20110706',
 '20110707',
 '20110708',
 '20110711',
 '20110712',
 '20110713',
 '20110714',
 '20110715',
 '20110718',
 '20110719',
 '20110720',
 '20110721',
 '20110722',
 '20110725',
 '20110726',
 '20110727',
 '20110728',
 '20110729',
 '20110801',
 '20110802',
 '20110803',
 '20110804',
 '20110805',
 '20110808',
 '20110809',
 '20110810',
 '20110811',
 '20110812',
 '20110816',
 '20110817',
 '20110818',
 '20110819',
 '20110822',
 '20110823',
 '20110824',
 '20110825',
 '20110826',
 '20110829',
 '20110830',
 '20110831',
 '20110901',
 '20110902',
 '20110905',
 '20110906',
 '20110907',
 '20110908',
 '20110909',
 '20110914',
 '20110915',
 '20110916',
 '20110919',
 '20110920',
 '20110921',
 '20110922',
 '20110923',
 '20110926',
 '20110927',
 '20110928',
 '20110929',
 '20110930',
 '20111004',
 '20111005',
 '20111006',
 '20111007',
 '20111010',
 '20111011',
 '20111012',
 '20111013',
 '20111014',
 '20111017',
 '20111018',
 '20111019',
 '20111020',
 '20111021',
 '20111024',
 '20111025',
 '20111026',
 '20111027',
 '20111028',
 '20111031',
 '20111101',
 '20111102',
 '20111103',
 '20111104',
 '20111107',
 '20111108',
 '20111109',
 '20111110',
 '20111111',
 '20111114',
 '20111115',
 '20111116',
 '20111117',
 '20111118',
 '20111121',
 '20111122',
 '20111123',
 '20111124',
 '20111125',
 '20111128',
 '20111129',
 '20111130',
 '20111201',
 '20111202',
 '20111205',
 '20111206',
 '20111207',
 '20111208',
 '20111209',
 '20111212',
 '20111213',
 '20111214',
 '20111215',
 '20111216',
 '20111219',
 '20111220',
 '20111221',
 '20111222',
 '20111223',
 '20111226',
 '20111227',
 '20111228',
 '20111229',
 '20120102',
 '20120103',
 '20120104',
 '20120105',
 '20120106',
 '20120109',
 '20120110',
 '20120111',
 '20120112',
 '20120113',
 '20120116',
 '20120117',
 '20120118',
 '20120119',
 '20120120',
 '20120125',
 '20120126',
 '20120127',
 '20120130',
 '20120131',
 '20120201',
 '20120202',
 '20120203',
 '20120206',
 '20120207',
 '20120208',
 '20120209',
 '20120210',
 '20120213',
 '20120214',
 '20120215',
 '20120216',
 '20120217',
 '20120220',
 '20120221',
 '20120222',
 '20120223',
 '20120224',
 '20120227',
 '20120228',
 '20120229',
 '20120302',
 '20120305',
 '20120306',
 '20120307',
 '20120308',
 '20120309',
 '20120312',
 '20120313',
 '20120314',
 '20120315',
 '20120316',
 '20120319',
 '20120320',
 '20120321',
 '20120322',
 '20120323',
 '20120326',
 '20120327',
 '20120328',
 '20120329',
 '20120330',
 '20120402',
 '20120403',
 '20120404',
 '20120405',
 '20120406',
 '20120409',
 '20120410',
 '20120412',
 '20120413',
 '20120416',
 '20120417',
 '20120418',
 '20120419',
 '20120420',
 '20120423',
 '20120424',
 '20120425',
 '20120426',
 '20120427',
 '20120430',
 '20120502',
 '20120503',
 '20120504',
 '20120507',
 '20120508',
 '20120509',
 '20120510',
 '20120511',
 '20120514',
 '20120515',
 '20120516',
 '20120517',
 '20120518',
 '20120521',
 '20120522',
 '20120523',
 '20120524',
 '20120525',
 '20120529',
 '20120530',
 '20120531',
 '20120601',
 '20120604',
 '20120605',
 '20120607',
 '20120608',
 '20120611',
 '20120612',
 '20120613',
 '20120614',
 '20120615',
 '20120618',
 '20120619',
 '20120620',
 '20120621',
 '20120622',
 '20120625',
 '20120626',
 '20120627',
 '20120628',
 '20120629',
 '20120702',
 '20120703',
 '20120704',
 '20120705',
 '20120706',
 '20120709',
 '20120710',
 '20120711',
 '20120712',
 '20120713',
 '20120716',
 '20120717',
 '20120718',
 '20120719',
 '20120720',
 '20120723',
 '20120724',
 '20120725',
 '20120726',
 '20120727',
 '20120730',
 '20120731',
 '20120801',
 '20120802',
 '20120803',
 '20120806',
 '20120807',
 '20120808',
 '20120809',
 '20120810',
 '20120813',
 '20120814',
 '20120816',
 '20120817',
 '20120820',
 '20120821',
 '20120822',
 '20120823',
 '20120824',
 '20120827',
 '20120828',
 '20120829',
 '20120830',
 '20120831',
 '20120903',
 '20120904',
 '20120905',
 '20120906',
 '20120907',
 '20120910',
 '20120911',
 '20120912',
 '20120913',
 '20120914',
 '20120917',
 '20120918',
 '20120919',
 '20120920',
 '20120921',
 '20120924',
 '20120925',
 '20120926',
 '20120927',
 '20120928',
 '20121002',
 '20121004',
 '20121005',
 '20121008',
 '20121009',
 '20121010',
 '20121011',
 '20121012',
 '20121015',
 '20121016',
 '20121017',
 '20121018',
 '20121019',
 '20121022',
 '20121023',
 '20121024',
 '20121025',
 '20121026',
 '20121029',
 '20121030',
 '20121031',
 '20121101',
 '20121102',
 '20121105',
 '20121106',
 '20121107',
 '20121108',
 '20121109',
 '20121112',
 '20121113',
 '20121114',
 '20121115',
 '20121116',
 '20121119',
 '20121120',
 '20121121',
 '20121122',
 '20121123',
 '20121126',
 '20121127',
 '20121128',
 '20121129',
 '20121130',
 '20121203',
 '20121204',
 '20121205',
 '20121206',
 '20121207',
 '20121210',
 '20121211',
 '20121212',
 '20121213',
 '20121214',
 '20121217',
 '20121218',
 '20121220',
 '20121221',
 '20121224',
 '20121226',
 '20121227',
 '20121228',
 '20130102',
 '20130103',
 '20130104',
 '20130107',
 '20130108',
 '20130109',
 '20130110',
 '20130111',
 '20130114',
 '20130115',
 '20130116',
 '20130117',
 '20130118',
 '20130121',
 '20130122',
 '20130123',
 '20130124',
 '20130125',
 '20130128',
 '20130129',
 '20130130',
 '20130131',
 '20130201',
 '20130204',
 '20130205',
 '20130206',
 '20130207',
 '20130208',
 '20130212',
 '20130213',
 '20130214',
 '20130215',
 '20130218',
 '20130219',
 '20130220',
 '20130221',
 '20130222',
 '20130225',
 '20130226',
 '20130227',
 '20130228',
 '20130304',
 '20130305',
 '20130306',
 '20130307',
 '20130308',
 '20130311',
 '20130312',
 '20130313',
 '20130314',
 '20130315',
 '20130318',
 '20130319',
 '20130320',
 '20130321',
 '20130322',
 '20130325',
 '20130326',
 '20130327',
 '20130328',
 '20130329',
 '20130401',
 '20130402',
 '20130403',
 '20130404',
 '20130405',
 '20130408',
 '20130409',
 '20130410',
 '20130411',
 '20130412',
 '20130415',
 '20130416',
 '20130417',
 '20130418',
 '20130419',
 '20130422',
 '20130423',
 '20130424',
 '20130425',
 '20130426',
 '20130429',
 '20130430',
 '20130502',
 '20130503',
 '20130506',
 '20130507',
 '20130508',
 '20130509',
 '20130510',
 '20130513',
 '20130514',
 '20130515',
 '20130516',
 '20130520',
 '20130521',
 '20130522',
 '20130523',
 '20130524',
 '20130527',
 '20130528',
 '20130529',
 '20130530',
 '20130531',
 '20130603',
 '20130604',
 '20130605',
 '20130607',
 '20130610',
 '20130611',
 '20130612',
 '20130613',
 '20130614',
 '20130617',
 '20130618',
 '20130619',
 '20130620',
 '20130621',
 '20130624',
 '20130625',
 '20130626',
 '20130627',
 '20130628',
 '20130701',
 '20130702',
 '20130703',
 '20130704',
 '20130705',
 '20130708',
 '20130709',
 '20130710',
 '20130711',
 '20130712',
 '20130715',
 '20130716',
 '20130717',
 '20130718',
 '20130719',
 '20130722',
 '20130723',
 '20130724',
 '20130725',
 '20130726',
 '20130729',
 '20130730',
 '20130731',
 '20130801',
 '20130802',
 '20130805',
 '20130806',
 '20130807',
 '20130808',
 '20130809',
 '20130812',
 '20130813',
 '20130814',
 '20130816',
 '20130819',
 '20130820',
 '20130821',
 '20130822',
 '20130823',
 '20130826',
 '20130827',
 '20130828',
 '20130829',
 '20130830',
 '20130902',
 '20130903',
 '20130904',
 '20130905',
 '20130906',
 '20130909',
 '20130910',
 '20130911',
 '20130912',
 '20130913',
 '20130916',
 '20130917',
 '20130923',
 '20130924',
 '20130925',
 '20130926',
 '20130927',
 '20130930',
 '20131001',
 '20131002',
 '20131004',
 '20131007',
 '20131008',
 '20131010',
 '20131011',
 '20131014',
 '20131015',
 '20131016',
 '20131017',
 '20131018',
 '20131021',
 '20131022',
 '20131023',
 '20131024',
 '20131025',
 '20131028',
 '20131029',
 '20131030',
 '20131031',
 '20131101',
 '20131104',
 '20131105',
 '20131106',
 '20131107',
 '20131108',
 '20131111',
 '20131112',
 '20131113',
 '20131114',
 '20131115',
 '20131118',
 '20131119',
 '20131120',
 '20131121',
 '20131122',
 '20131125',
 '20131126',
 '20131127',
 '20131128',
 '20131129',
 '20131202',
 '20131203',
 '20131204',
 '20131205',
 '20131206',
 '20131209',
 '20131210',
 '20131211',
 '20131212',
 '20131213',
 '20131216',
 '20131217',
 '20131218',
 '20131219',
 '20131220',
 '20131223',
 '20131224',
 '20131226',
 '20131227',
 '20131230',
 '20140102',
 '20140103',
 '20140106',
 '20140107',
 '20140108',
 '20140109',
 ...]

In [25]:
len(lv2_index_rename)

2466

In [26]:
# Data Guide에서 받은 자료에 있는 모든 기업 & 기업코드를 토대로 만든 symbol_dic을 이용하여 lv2_companies에 있는 기업들의 기업코드를 symbol에 저장
symbol = []
for corp in lv2_companies:
    symbol.append(symbol_dic[corp])
symbol

['006840',
 '027410',
 '282330',
 '138930',
 '001040',
 '079160',
 '000120',
 '097950',
 '005830',
 '000990',
 '139130',
 '114090',
 '078930',
 '006360',
 '007070',
 '012630',
 '294870',
 '082740',
 '001060',
 '096760',
 '105560',
 '002380',
 '009440',
 '001940',
 '025000',
 '030200',
 '033780',
 '093050',
 '003550',
 '034220',
 '001120',
 '068870',
 '051900',
 '032640',
 '011070',
 '066570',
 '108670',
 '051910',
 '079550',
 '006260',
 '010120',
 '035420',
 '005940',
 '010060',
 '005490',
 '100840',
 '064960',
 '003570',
 '010950',
 '034120',
 '034730',
 '011790',
 '001740',
 '006120',
 '096770',
 '285130',
 '017670',
 '000660',
 '005610',
 '011810',
 '077970',
 '067250',
 '071970',
 '084870',
 '035250',
 '000050',
 '010130',
 '002240',
 '009290',
 '017900',
 '007690',
 '002990',
 '011780',
 '001210',
 '073240',
 '000270',
 '024110',
 '003920',
 '025860',
 '002350',
 '251270',
 '006280',
 '005250',
 '004370',
 '019680',
 '005270',
 '004130',
 '008060',
 '000210',
 '001680',
 '047040',
 '042660',
 '069620',
 '000430',
 '006650',
 '001440',
 '084010',
 '001790',
 '001130',
 '003490',
 '008000',
 '001230',
 '016380',
 '026960',
 '000640',
 '170900',
 '001520',
 '049770',
 '014820',
 '004890',
 '000020',
 '000150',
 '241560',
 '042670',
 '034020',
 '013570',
 '007340',
 '115390',
 '023530',
 '004000',
 '004990',
 '005300',
 '011170',
 '002270',
 '071840',
 '204320',
 '008560',
 '009680',
 '009580',
 '009200',
 '033920',
 '006800',
 '037620',
 '007210',
 '003850',
 '003000',
 '005280',
 '005180',
 '008040',
 '005090',
 '006400',
 '028260',
 '207940',
 '032830',
 '018260',
 '028050',
 '009150',
 '005930',
 '010140',
 '016360',
 '029780',
 '000810',
 '145990',
 '003940',
 '000070',
 '005680',
 '005500',
 '007860',
 '008490',
 '004490',
 '001430',
 '003030',
 '091090',
 '033530',
 '027970',
 '068270',
 '004430',
 '029530',
 '104110',
 '004170',
 '031430',
 '055550',
 '003410',
 '003620',
 '002790',
 '090430',
 '002030',
 '010780',
 '021570',
 '003190',
 '018250',
 '005850',
 '012750',
 '078520',
 '036570',
 '085310',
 '111770',
 '003520',
 '000670',
 '007310',
 '271560',
 '001800',
 '004940',
 '053000',
 '000030',
 '103130',
 '014830',
 '003640',
 '000700',
 '000100',
 '008730',
 '214320',
 '139480',
 '005950',
 '014990',
 '000230',
 '003120',
 '003200',
 '007570',
 '020760',
 '020150',
 '103590',
 '033240',
 '009720',
 '030000',
 '001300',
 '002620',
 '004700',
 '000480',
 '185750',
 '001630',
 '035720',
 '006380',
 '011400',
 '064420',
 '007810',
 '192820',
 '044820',
 '002020',
 '120110',
 '021240',
 '192400',
 '015590',
 '005740',
 '003240',
 '005690',
 '036580',
 '028670',
 '016800',
 '047050',
 '051310',
 '103140',
 '086790',
 '103150',
 '000080',
 '000140',
 '036460',
 '071050',
 '008320',
 '025540',
 '002960',
 '015760',
 '002300',
 '009540',
 '104700',
 '017960',
 '161890',
 '161390',
 '000240',
 '047810',
 '002390',
 '060980',
 '042700',
 '008930',
 '128940',
 '009240',
 '020000',
 '105630',
 '014680',
 '004710',
 '004150',
 '018880',
 '009420',
 '006390',
 '003300',
 '051600',
 '052690',
 '097230',
 '003480',
 '000880',
 '088350',
 '009830',
 '012450',
 '025850',
 '000720',
 '005440',
 '086280',
 '064350',
 '079430',
 '012330',
 '010620',
 '069960',
 '011200',
 '017800',
 '011210',
 '004020',
 '267250',
 '003450',
 '005380',
 '010520',
 '001450',
 '057050',
 '008770',
 '010690',
 '004800',
 '298040',
 '093370',
 '081660',
 '079980',
 '069260']

In [27]:
len(symbol)

310

In [28]:
def get_closing_price(code):  # 개별기업코드 입력 시 종가 반환
    
    import FinanceDataReader as fdr
   
    df = fdr.DataReader(code, start = '2010-01-01', end = '2019-12-31')
    df = df['Close']
    
    return df

In [29]:
def get_return(code):  # 개별기업코드 입력 시 수익률 반환
    
    import FinanceDataReader as fdr
    
    df = fdr.DataReader(code, start = '2010-01-01', end = '2019-12-31')
    df = df['Change']
    
    return df

In [32]:
## 필요 없음
def get_monthly_price(code):  # 개별기업코드 입력 시 월별 종가 반환
    
    from pykrx import stock
    
    df = stock.get_market_ohlcv_by_date("20100101", "20191231", code, "m")
    df = df['종가']
    
    return df

새로운 방법 : concat하기 → columns의 이름을 바꿔줘야 함

In [31]:
# '알루코' 삭제 → 주가 데이터 없음
del symbol[178]
del lv2_companies[178]
del lv2_companies_rename[178]

In [114]:
price_df = pd.DataFrame()
for process,x in enumerate(symbol):
    print("Process : {} | Total : {}".format(process+1,len(symbol)), end='\r')
    char_price_df = get_closing_price(x)
    price_df = pd.concat([price_df, char_price_df], axis=1)

In [33]:
## 필요 없음
monthly_price_df = pd.DataFrame()
for process,x in enumerate(symbol):
    print("Process : {} | Total : {}".format(process+1,len(symbol)), end='\r')
    char_monthly_price_df = get_monthly_price(x)
    monthly_price_df = pd.concat([monthly_price_df, char_monthly_price_df], axis=1)

In [34]:
## 필요 없음
monthly_price_df

,종가,종가,종가,종가,종가,종가,종가,종가,종가,종가,...,종가,종가,종가,종가,종가,종가,종가,종가,종가,종가
2010-01-31,9955,NaN,NaN,NaN,63367,21500,53800,209000,33550,6080,...,17750,NaN,19850,4100,48113,NaN,3775,NaN,NaN,16859
2010-02-28,9580,NaN,NaN,NaN,64876,22900,56100,209500,31500,6250,...,18900,NaN,20000,4960,51782,NaN,3932,NaN,NaN,16829
2010-03-31,11145,NaN,NaN,NaN,63556,23800,66100,225000,32300,7370,...,18300,NaN,22700,6680,48053,NaN,3790,NaN,NaN,16813
2010-04-30,11364,NaN,NaN,NaN,60821,23300,62400,222000,35300,8420,...,20650,NaN,22450,7650,46811,NaN,3618,NaN,NaN,16531
2010-05-31,11364,NaN,NaN,NaN,57144,24150,55500,214000,33100,10600,...,22550,NaN,21200,11450,40183,NaN,3153,NaN,NaN,15028
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-08-31,33300,5750.0,203500.0,6700.0,81500,33550,143000,228500,47900,14700,...,23900,93100.0,78800,2825,86400,35400.0,9100,57200.0,6310.0,21300
2019-09-30,31450,6000.0,197000.0,7190.0,82000,33400,144500,234500,51600,16000,...,26400,91500.0,86200,3450,83800,31450.0,8480,57900.0,6170.0,21400
2019-10-31,31300,5750.0,178000.0,6950.0,82400,33750,157500,228500,50500,17000,...,25250,84500.0,77500,3650,82700,28300.0,8440,57600.0,5800.0,22100
2019-11-30,31500,5570.0,168000.0,6960.0,92100,36750,157500,248000,55700,19000,...,28000,85000.0,84700,3555,79400,25350.0,7830,51600.0,6010.0,21500
2019-12-31,34600,5600.0,169500.0,7660.0,96600,34550,155000,252500,52300,27600,...,26950,80500.0,90800,3270,79100,26650.0,8170,53000.0,6090.0,21150

In [109]:
stock.get_market_ticker_name('021570')

'알루코'

In [110]:
fdr.DataReader('021570', start = '2010-01-01', end = '2019-12-31')

Empty DataFrame
Columns: []
Index: []

In [115]:
price_df

,Close,Close,Close,Close,Close,Close,Close,Close,Close,Close,...,Close,Close,Close,Close,Close,Close,Close,Close,Close,Close
2010-01-04,10331,NaN,NaN,NaN,58652,21100,54500,207000,34200,7500,...,19450,NaN,21950,3915,50480,NaN,3726,NaN,NaN,17885
2010-01-05,10206,NaN,NaN,NaN,59595,21200,54400,220000,33600,7550,...,19300,NaN,22300,3785,52255,NaN,3702,NaN,NaN,17312
2010-01-06,10206,NaN,NaN,NaN,59595,21600,56400,220500,35450,7410,...,20200,NaN,22200,3910,54859,NaN,3755,NaN,NaN,17613
2010-01-07,10300,NaN,NaN,NaN,60444,21750,56600,218000,35650,7460,...,20200,NaN,21550,3865,53143,NaN,3785,NaN,NaN,17312
2010-01-08,10362,NaN,NaN,NaN,63556,22800,57600,218000,35300,7510,...,20000,NaN,21350,3975,55037,NaN,3804,NaN,NaN,17432
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-12-23,33500,5570.0,165500.0,7870.0,96500,34900,151500,243500,54600,25950,...,27900,81000.0,86300,3145,82600,26400.0,7910,53900.0,6080.0,22450
2019-12-24,34500,5530.0,165500.0,7850.0,96000,34100,150000,242000,54500,26650,...,27900,81000.0,84000,3270,83800,26150.0,8020,54000.0,6120.0,22650
2019-12-26,34900,5580.0,165500.0,7770.0,97000,33800,150000,243000,54500,26650,...,27950,81000.0,83800,3250,84300,26200.0,7970,52600.0,6250.0,22450
2019-12-27,34850,5600.0,168500.0,7620.0,96400,33950,154500,250000,52800,28150,...,27150,80200.0,87300,3270,79600,26300.0,8110,53800.0,6090.0,21300
2019-12-30,34600,5600.0,169500.0,7660.0,96600,34550,155000,252500,52300,27600,...,26950,80500.0,90800,3270,79100,26650.0,8170,53000.0,6090.0,21150

In [117]:
price_df.columns = lv2_companies_rename
price_df.columns

Index(['AK홀딩스', 'BGF', 'BGF리테일', 'BNK금융지주', 'CJ', 'CJ CGV', 'CJ대한통운', 'CJ제일제당',
       'DB손해보험', 'DB하이텍',
       ...
       '현대해상', '현대홈쇼핑', '호텔신라', '화신', '효성', '효성중공업', '후성', '휠라홀딩스', '휴비스',
       '휴켐스'],
      dtype='object', length=309)

In [128]:
price_df.index = lv2_index_rename
price_df

,AK홀딩스,BGF,BGF리테일,BNK금융지주,CJ,CJ CGV,CJ대한통운,CJ제일제당,DB손해보험,DB하이텍,...,현대해상,현대홈쇼핑,호텔신라,화신,효성,효성중공업,후성,휠라홀딩스,휴비스,휴켐스
20100104,10331,NaN,NaN,NaN,58652,21100,54500,207000,34200,7500,...,19450,NaN,21950,3915,50480,NaN,3726,NaN,NaN,17885
20100105,10206,NaN,NaN,NaN,59595,21200,54400,220000,33600,7550,...,19300,NaN,22300,3785,52255,NaN,3702,NaN,NaN,17312
20100106,10206,NaN,NaN,NaN,59595,21600,56400,220500,35450,7410,...,20200,NaN,22200,3910,54859,NaN,3755,NaN,NaN,17613
20100107,10300,NaN,NaN,NaN,60444,21750,56600,218000,35650,7460,...,20200,NaN,21550,3865,53143,NaN,3785,NaN,NaN,17312
20100108,10362,NaN,NaN,NaN,63556,22800,57600,218000,35300,7510,...,20000,NaN,21350,3975,55037,NaN,3804,NaN,NaN,17432
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20191223,33500,5570.0,165500.0,7870.0,96500,34900,151500,243500,54600,25950,...,27900,81000.0,86300,3145,82600,26400.0,7910,53900.0,6080.0,22450
20191224,34500,5530.0,165500.0,7850.0,96000,34100,150000,242000,54500,26650,...,27900,81000.0,84000,3270,83800,26150.0,8020,54000.0,6120.0,22650
20191226,34900,5580.0,165500.0,7770.0,97000,33800,150000,243000,54500,26650,...,27950,81000.0,83800,3250,84300,26200.0,7970,52600.0,6250.0,22450
20191227,34850,5600.0,168500.0,7620.0,96400,33950,154500,250000,52800,28150,...,27150,80200.0,87300,3270,79600,26300.0,8110,53800.0,6090.0,21300
20191230,34600,5600.0,169500.0,7660.0,96600,34550,155000,252500,52300,27600,...,26950,80500.0,90800,3270,79100,26650.0,8170,53000.0,6090.0,21150

In [129]:
price_df.to_csv(r'C:\Users\PC\OneDrive\Data Science\Weak-supervision\생존편향 제거\완료된 데이터\price_df.csv', encoding='euc-kr')

같은 방법으로 수익률 데이터 가져오기

In [120]:
return_df = pd.DataFrame()
for process,x in enumerate(symbol):
    print("Process : {} | Total : {}".format(process+1,len(symbol)), end='\r')
    char_return_df = get_return(x)
    return_df = pd.concat([return_df, char_return_df], axis=1)

In [121]:
return_df

,Change,Change,Change,Change,Change,Change,Change,Change,Change,Change,...,Change,Change,Change,Change,Change,Change,Change,Change,Change,Change
2010-01-04,-0.002992,NaN,NaN,NaN,-0.007983,-0.040909,-0.038801,0.007299,0.055556,0.060820,...,0.040107,NaN,0.065534,0.018205,0.001170,NaN,-0.006665,NaN,NaN,-0.024650
2010-01-05,-0.012100,NaN,NaN,NaN,0.016078,0.004739,-0.001835,0.062802,-0.017544,0.006667,...,-0.007712,NaN,0.015945,-0.033206,0.035162,NaN,-0.006441,NaN,NaN,-0.032038
2010-01-06,0.000000,NaN,NaN,NaN,0.000000,0.018868,0.036765,0.002273,0.055060,-0.018543,...,0.046632,NaN,-0.004484,0.033025,0.049833,NaN,0.014317,NaN,NaN,0.017387
2010-01-07,0.009210,NaN,NaN,NaN,0.014246,0.006944,0.003546,-0.011338,0.005642,0.006748,...,0.000000,NaN,-0.029279,-0.011509,-0.031280,NaN,0.007989,NaN,NaN,-0.017090
2010-01-08,0.006019,NaN,NaN,NaN,0.051486,0.048276,0.017668,0.000000,-0.009818,0.006702,...,-0.009901,NaN,-0.009281,0.028461,0.035640,NaN,0.005020,NaN,NaN,0.006932
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-12-23,0.007519,0.012727,0.015337,-0.002535,0.002077,-0.002857,-0.013029,0.008282,-0.003650,-0.022599,...,0.005405,0.003717,0.002323,0.006400,0.012255,0.011494,-0.027060,0.022770,0.001647,0.004474
2019-12-24,0.029851,-0.007181,0.000000,-0.002541,-0.005181,-0.022923,-0.009901,-0.006160,-0.001832,0.026975,...,0.000000,0.000000,-0.026651,0.039746,0.014528,-0.009470,0.013906,0.001855,0.006579,0.008909
2019-12-26,0.011594,0.009042,0.000000,-0.010191,0.010417,-0.008798,0.000000,0.004132,0.000000,0.000000,...,0.001792,0.000000,-0.002381,-0.006116,0.005967,0.001912,-0.006234,-0.025926,0.021242,-0.008830
2019-12-27,-0.001433,0.003584,0.018127,-0.019305,-0.006186,0.004438,0.030000,0.028807,-0.031193,0.056285,...,-0.028623,-0.009877,0.041766,0.006154,-0.055753,0.003817,0.017566,0.022814,-0.025600,-0.051225
2019-12-30,-0.007174,0.000000,0.005935,0.005249,0.002075,0.017673,0.003236,0.010000,-0.009470,-0.019538,...,-0.007366,0.003741,0.040092,0.000000,-0.006281,0.013308,0.007398,-0.014870,0.000000,-0.007042

In [122]:
return_df.columns = lv2_companies_rename
return_df.columns

Index(['AK홀딩스', 'BGF', 'BGF리테일', 'BNK금융지주', 'CJ', 'CJ CGV', 'CJ대한통운', 'CJ제일제당',
       'DB손해보험', 'DB하이텍',
       ...
       '현대해상', '현대홈쇼핑', '호텔신라', '화신', '효성', '효성중공업', '후성', '휠라홀딩스', '휴비스',
       '휴켐스'],
      dtype='object', length=309)

In [130]:
return_df.index = lv2_index_rename
return_df

,AK홀딩스,BGF,BGF리테일,BNK금융지주,CJ,CJ CGV,CJ대한통운,CJ제일제당,DB손해보험,DB하이텍,...,현대해상,현대홈쇼핑,호텔신라,화신,효성,효성중공업,후성,휠라홀딩스,휴비스,휴켐스
20100104,-0.002992,NaN,NaN,NaN,-0.007983,-0.040909,-0.038801,0.007299,0.055556,0.060820,...,0.040107,NaN,0.065534,0.018205,0.001170,NaN,-0.006665,NaN,NaN,-0.024650
20100105,-0.012100,NaN,NaN,NaN,0.016078,0.004739,-0.001835,0.062802,-0.017544,0.006667,...,-0.007712,NaN,0.015945,-0.033206,0.035162,NaN,-0.006441,NaN,NaN,-0.032038
20100106,0.000000,NaN,NaN,NaN,0.000000,0.018868,0.036765,0.002273,0.055060,-0.018543,...,0.046632,NaN,-0.004484,0.033025,0.049833,NaN,0.014317,NaN,NaN,0.017387
20100107,0.009210,NaN,NaN,NaN,0.014246,0.006944,0.003546,-0.011338,0.005642,0.006748,...,0.000000,NaN,-0.029279,-0.011509,-0.031280,NaN,0.007989,NaN,NaN,-0.017090
20100108,0.006019,NaN,NaN,NaN,0.051486,0.048276,0.017668,0.000000,-0.009818,0.006702,...,-0.009901,NaN,-0.009281,0.028461,0.035640,NaN,0.005020,NaN,NaN,0.006932
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20191223,0.007519,0.012727,0.015337,-0.002535,0.002077,-0.002857,-0.013029,0.008282,-0.003650,-0.022599,...,0.005405,0.003717,0.002323,0.006400,0.012255,0.011494,-0.027060,0.022770,0.001647,0.004474
20191224,0.029851,-0.007181,0.000000,-0.002541,-0.005181,-0.022923,-0.009901,-0.006160,-0.001832,0.026975,...,0.000000,0.000000,-0.026651,0.039746,0.014528,-0.009470,0.013906,0.001855,0.006579,0.008909
20191226,0.011594,0.009042,0.000000,-0.010191,0.010417,-0.008798,0.000000,0.004132,0.000000,0.000000,...,0.001792,0.000000,-0.002381,-0.006116,0.005967,0.001912,-0.006234,-0.025926,0.021242,-0.008830
20191227,-0.001433,0.003584,0.018127,-0.019305,-0.006186,0.004438,0.030000,0.028807,-0.031193,0.056285,...,-0.028623,-0.009877,0.041766,0.006154,-0.055753,0.003817,0.017566,0.022814,-0.025600,-0.051225
20191230,-0.007174,0.000000,0.005935,0.005249,0.002075,0.017673,0.003236,0.010000,-0.009470,-0.019538,...,-0.007366,0.003741,0.040092,0.000000,-0.006281,0.013308,0.007398,-0.014870,0.000000,-0.007042

In [131]:
return_df.to_csv(r'C:\Users\PC\OneDrive\Data Science\Weak-supervision\생존편향 제거\완료된 데이터\return_df.csv', encoding='euc-kr')